// flow-typed signature: c4350080db48f11c5c7accf623773b6d
// flow-typed version: <<STUB>>/@authing/sso_v1.5.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@authing/sso'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@authing/sso' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@authing/sso/babel.config' {
  declare module.exports: any;
}

declare module '@authing/sso/dist/AuthingSSO.common' {
  declare module.exports: any;
}

declare module '@authing/sso/dist/AuthingSSO.umd' {
  declare module.exports: any;
}

declare module '@authing/sso/dist/AuthingSSO.umd.min' {
  declare module.exports: any;
}

declare module '@authing/sso/src/lib/gql/queryOAuthAppInfoByAppID' {
  declare module.exports: any;
}

declare module '@authing/sso/src/lib/gql/queryOIDCAppInfoByAppID' {
  declare module.exports: any;
}

declare module '@authing/sso/src/lib/gql/querySAMLServiceProviderInfoByAppID' {
  declare module.exports: any;
}

declare module '@authing/sso/src/lib/graphql' {
  declare module.exports: any;
}

declare module '@authing/sso/src/lib' {
  declare module.exports: any;
}

declare module '@authing/sso/src/main' {
  declare module.exports: any;
}

declare module '@authing/sso/vue.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@authing/sso/babel.config.js' {
  declare module.exports: $Exports<'@authing/sso/babel.config'>;
}
declare module '@authing/sso/dist/AuthingSSO.common.js' {
  declare module.exports: $Exports<'@authing/sso/dist/AuthingSSO.common'>;
}
declare module '@authing/sso/dist/AuthingSSO.umd.js' {
  declare module.exports: $Exports<'@authing/sso/dist/AuthingSSO.umd'>;
}
declare module '@authing/sso/dist/AuthingSSO.umd.min.js' {
  declare module.exports: $Exports<'@authing/sso/dist/AuthingSSO.umd.min'>;
}
declare module '@authing/sso/src/lib/gql/queryOAuthAppInfoByAppID.js' {
  declare module.exports: $Exports<'@authing/sso/src/lib/gql/queryOAuthAppInfoByAppID'>;
}
declare module '@authing/sso/src/lib/gql/queryOIDCAppInfoByAppID.js' {
  declare module.exports: $Exports<'@authing/sso/src/lib/gql/queryOIDCAppInfoByAppID'>;
}
declare module '@authing/sso/src/lib/gql/querySAMLServiceProviderInfoByAppID.js' {
  declare module.exports: $Exports<'@authing/sso/src/lib/gql/querySAMLServiceProviderInfoByAppID'>;
}
declare module '@authing/sso/src/lib/graphql.js' {
  declare module.exports: $Exports<'@authing/sso/src/lib/graphql'>;
}
declare module '@authing/sso/src/lib/index' {
  declare module.exports: $Exports<'@authing/sso/src/lib'>;
}
declare module '@authing/sso/src/lib/index.js' {
  declare module.exports: $Exports<'@authing/sso/src/lib'>;
}
declare module '@authing/sso/src/main.js' {
  declare module.exports: $Exports<'@authing/sso/src/main'>;
}
declare module '@authing/sso/vue.config.js' {
  declare module.exports: $Exports<'@authing/sso/vue.config'>;
}
