// flow-typed signature: f41abb11b95bd2420c0621c7550e6e11
// flow-typed version: <<STUB>>/@cliqz/adblocker-electron_v1.17.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cliqz/adblocker-electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cliqz/adblocker-electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cliqz/adblocker-electron/dist/cjs/adblocker' {
  declare module.exports: any;
}

declare module '@cliqz/adblocker-electron/dist/es6/adblocker' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cliqz/adblocker-electron/dist/cjs/adblocker.js' {
  declare module.exports: $Exports<'@cliqz/adblocker-electron/dist/cjs/adblocker'>;
}
declare module '@cliqz/adblocker-electron/dist/es6/adblocker.js' {
  declare module.exports: $Exports<'@cliqz/adblocker-electron/dist/es6/adblocker'>;
}
