import { AutoUnpackNativesPlugin } from '@electron-forge/plugin-auto-unpack-natives';
import { VitePlugin } from '@electron-forge/plugin-vite';
import type { ForgeConfig } from '@electron-forge/shared-types';
import { readJsonSync } from 'fs-extra';
import path from 'path';
import afterPack from './scripts/afterPack';
import { prepareSquirrelVendor, SQUIRREL_VENDOR_DIR } from './scripts/prepareSquirrelVendor';

const packageJson = readJsonSync(path.join(__dirname, 'package.json')) as { description: string };
const supportedLanguages = readJsonSync(path.join(__dirname, 'localization', 'supportedLanguages.json')) as Record<string, string>;

const { description } = packageJson;
// Get list of supported language codes from centralized config
const supportedLanguageCodes = Object.keys(supportedLanguages);

type MacSigningPackagerConfig = Pick<NonNullable<ForgeConfig['packagerConfig']>, 'osxSign'>;

/**
 * Give local macOS test packages a code identity so TCC can attribute access
 * performed by Electron UtilityProcess helpers. This is deliberately opt-in:
 * release builds must continue to use an explicit distribution-signing setup.
 */
export function getLocalAdHocMacSigningPackagerConfig(environment: NodeJS.ProcessEnv): MacSigningPackagerConfig {
  if (environment.TIDGI_LOCAL_ADHOC_SIGN !== '1') return {};
  return {
    osxSign: {
      identity: '-',
      identityValidation: false,
      preAutoEntitlements: false,
      optionsForFile: () => ({
        hardenedRuntime: false,
        timestamp: 'none',
      }),
    },
  };
}

const config: ForgeConfig = {
  packagerConfig: {
    name: 'TidGi',
    executableName: 'tidgi',
    quiet: false,
    win32metadata: {
      CompanyName: 'TiddlyWiki Community',
      OriginalFilename: 'TidGi Desktop',
    },
    protocols: [
      {
        name: 'TidGi Launch Protocol',
        schemes: ['tidgi'],
      },
    ],
    // Let Electron Packager select the platform-specific file extension
    // (.ico on Windows, .icns on macOS, and .png on Linux).
    icon: 'build-resources/icon',
    asar: {
      // Unpack worker files, utility process files, native modules path, and ALL .node binaries (including better-sqlite3)
      // UtilityProcess files must be unpacked because utilityProcess.fork() reads from the
      // real filesystem, unlike Worker which can read from inside an asar.
      unpack: '{**/.webpack/main/*.worker.*,**/.webpack/main/*Worker*,**/.webpack/main/native_modules/path.txt,**/{.**,**}/**/*.node}',
    },
    extraResource: [
      'localization',
      'template/wiki',
      'build-resources/tidgiMiniWindow@2x.png',
      'build-resources/tidgiMiniWindowTemplate@2x.png',
      // Linux BrowserWindow icons are loaded at runtime rather than embedded in the executable.
      'build-resources/icon.png',
      // Packaged for squirrelStartup to copy to %LocalAppData%\tidgi\app.ico (uninstall DisplayIcon).
      'build-resources/icon.ico',
    ],
    // @ts-expect-error - mac config is valid
    mac: {
      category: 'productivity',
      target: 'dmg',
      icon: 'build-resources/icon.icns',
      electronLanguages: supportedLanguageCodes,
    },
    extendInfo: {
      NSCameraUsageDescription: 'TidGi uses the camera only when you scan a signed MemeLoop device pairing QR code.',
    },
    appBundleId: 'com.tidgi',
    ...getLocalAdHocMacSigningPackagerConfig(process.env),
  },
  hooks: {
    packageAfterPrune: afterPack,
    // Patch Setup.exe so the Windows installer "Open setup log" button opens SquirrelTemp
    // (stock electron-winstaller Setup looks for missing SquirrelSetup.log).
    preMake: async () => {
      if (process.platform === 'win32') {
        prepareSquirrelVendor();
      }
    },
  },
  makers: [
    {
      name: '@electron-forge/maker-squirrel',
      platforms: ['win32'],
      config: (arch: string) => {
        return {
          setupExe: `Install-TidGi-Windows-${arch}.exe`,
          setupIcon: 'build-resources/icon-installer.ico',
          description,
          // Do not set iconUrl: Squirrel downloads it synchronously at end of install and can hang
          // for minutes when GitHub raw is unreachable. Template omits <iconUrl> entirely.
          nuspecTemplate: 'build-resources/tidgi.nuspectemplate',
          // Windows-only: generated by hooks.preMake → prepareSquirrelVendor().
          // Not used on macOS/Linux makers (this maker is platforms: ['win32'] only).
          ...(process.platform === 'win32' ? { vendorDirectory: SQUIRREL_VENDOR_DIR } : {}),
        };
      },
    },
    {
      name: '@electron-forge/maker-msix',
      platforms: ['win32'],
      config: {
        packageAssets: 'build-resources/icon.ico',
        sign: false,
        manifestVariables: {
          publisher: 'CN=TiddlyWiki Community',
        },
      },
    },
    {
      name: '@electron-forge/maker-zip',
      platforms: ['darwin'],
      config: {},
    },
    {
      name: '@electron-forge/maker-deb',
      platforms: ['linux'],
      config: {
        options: {
          maintainer: 'Lin Onetwo <linonetwo012@gmail.com>',
          mimeType: ['x-scheme-handler/tidgi'],
          // electron-installer-debian otherwise installs its bundled Electron icon.
          icon: 'build-resources/icon.png',
        },
      },
    },
    {
      name: '@electron-forge/maker-rpm',
      platforms: ['linux'],
      config: {
        options: {
          maintainer: 'Lin Onetwo <linonetwo012@gmail.com>',
          mimeType: ['x-scheme-handler/tidgi'],
          icon: 'build-resources/icon.png',
        },
      },
    },
  ],
  plugins: [
    new AutoUnpackNativesPlugin({}),
    new VitePlugin({
      // `build` can specify multiple entry builds, which can be Main process, Preload scripts, Worker process, etc.
      build: [
        {
          // `entry` is an alias for `build.lib.entry` in the corresponding file of `config`.
          entry: 'src/main.ts',
          config: 'vite.main.config.ts',
          target: 'main',
        },
        {
          entry: 'src/preload/index.ts',
          config: 'vite.preload.config.ts',
          target: 'preload',
        },
      ],
      renderer: [
        {
          name: 'main_window',
          config: 'vite.renderer.config.ts',
        },
      ],
    }),
  ],
};

export default config;
