packages:
  - packages/*

overrides:
  prebuild-install: latest
  node-addon-api: "^7.1.1"

onlyBuiltDependencies:
  - "@swc/core"
  - better-sqlite3
  - dprint
  - dugite
  - electron
  - electron-winstaller
  - esbuild
  - nsfw
  - registry-js
  - unrs-resolver

nodeLinker: hoisted

allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  dprint: true
  dugite: true
  electron: true
  electron-winstaller: true
  esbuild: true
  nsfw: true
  registry-js: true
  unrs-resolver: true
