packages:
  - packages/*
allowBuilds:
  '@swc/core': set this to true or false
  better-sqlite3: set this to true or false
  dprint: set this to true or false
  dugite: set this to true or false
  electron: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
  nsfw: set this to true or false
  registry-js: set this to true or false
  unrs-resolver: set this to true or false
