packages:
  - packages/*

onlyBuiltDependencies:
  - "@swc/core"
  - better-sqlite3
  - dprint
  - dugite
  - electron
  - electron-winstaller
  - esbuild
  - nsfw
  - registry-js
  - unrs-resolver

nodeLinker: hoisted
