export default {
  Agent: Symbol.for('Agent'),
  Authentication: Symbol.for('Authentication'),
  Context: Symbol.for('Context'),
  Database: Symbol.for('Database'),
  DeepLink: Symbol.for('DeepLinkService'),
  ExternalAPI: Symbol.for('ExternalAPI'),
  Git: Symbol.for('Git'),
  MenuService: Symbol.for('MenuService'),
  NativeService: Symbol.for('NativeService'),
  NotificationService: Symbol.for('NotificationService'),
  Pages: Symbol.for('Pages'),
  Preference: Symbol.for('Preference'),
  Sync: Symbol.for('Sync'),
  SystemPreference: Symbol.for('SystemPreference'),
  ThemeService: Symbol.for('ThemeService'),
  Updater: Symbol.for('Updater'),
  View: Symbol.for('View'),
  Wiki: Symbol.for('Wiki'),
  WikiGitWorkspace: Symbol.for('WikiGitWorkspace'),
  Window: Symbol.for('Window'),
  Workspace: Symbol.for('Workspace'),
  WorkspaceView: Symbol.for('WorkspaceView'),
};
