// flow-typed signature: e7add84fe9e7da2bdada31224ca1ed37
// flow-typed version: <<STUB>>/algoliasearch_v4.2.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'algoliasearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'algoliasearch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'algoliasearch/dist/algoliasearch-lite.esm.browser' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearch-lite.umd' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearch.cjs' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearch.esm.browser' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearch.umd' {
  declare module.exports: any;
}

declare module 'algoliasearch/lite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'algoliasearch/dist/algoliasearch-lite.esm.browser.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch-lite.esm.browser'>;
}
declare module 'algoliasearch/dist/algoliasearch-lite.umd.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch-lite.umd'>;
}
declare module 'algoliasearch/dist/algoliasearch.cjs.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch.cjs'>;
}
declare module 'algoliasearch/dist/algoliasearch.esm.browser.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch.esm.browser'>;
}
declare module 'algoliasearch/dist/algoliasearch.umd.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch.umd'>;
}
declare module 'algoliasearch/index' {
  declare module.exports: $Exports<'algoliasearch'>;
}
declare module 'algoliasearch/index.js' {
  declare module.exports: $Exports<'algoliasearch'>;
}
declare module 'algoliasearch/lite.js' {
  declare module.exports: $Exports<'algoliasearch/lite'>;
}
