// flow-typed signature: b202b62cbb0960f1336a72557605bb2d
// flow-typed version: <<STUB>>/cross-env_v7.0.2/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cross-env/src/bin/cross-env-shell' {
  declare module.exports: any;
}

declare module 'cross-env/src/bin/cross-env' {
  declare module.exports: any;
}

declare module 'cross-env/src/command' {
  declare module.exports: any;
}

declare module 'cross-env/src' {
  declare module.exports: any;
}

declare module 'cross-env/src/is-windows' {
  declare module.exports: any;
}

declare module 'cross-env/src/variable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cross-env/src/bin/cross-env-shell.js' {
  declare module.exports: $Exports<'cross-env/src/bin/cross-env-shell'>;
}
declare module 'cross-env/src/bin/cross-env.js' {
  declare module.exports: $Exports<'cross-env/src/bin/cross-env'>;
}
declare module 'cross-env/src/command.js' {
  declare module.exports: $Exports<'cross-env/src/command'>;
}
declare module 'cross-env/src/index' {
  declare module.exports: $Exports<'cross-env/src'>;
}
declare module 'cross-env/src/index.js' {
  declare module.exports: $Exports<'cross-env/src'>;
}
declare module 'cross-env/src/is-windows.js' {
  declare module.exports: $Exports<'cross-env/src/is-windows'>;
}
declare module 'cross-env/src/variable.js' {
  declare module.exports: $Exports<'cross-env/src/variable'>;
}
