// flow-typed signature: ead051a4e8f156aec308d44adc19904a
// flow-typed version: <<STUB>>/darkreader_v4.9.21/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'darkreader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'darkreader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'darkreader/darkreader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'darkreader/darkreader.js' {
  declare module.exports: $Exports<'darkreader/darkreader'>;
}
