// flow-typed signature: 5c76c3a6ba663ed1b97d3b4a24e12013
// flow-typed version: <<STUB>>/dugite_v1.91.3/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dugite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dugite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dugite/build/lib/errors' {
  declare module.exports: any;
}

declare module 'dugite/build/lib/git-environment' {
  declare module.exports: any;
}

declare module 'dugite/build/lib/git-process' {
  declare module.exports: any;
}

declare module 'dugite/build/lib' {
  declare module.exports: any;
}

declare module 'dugite/jest.external.config' {
  declare module.exports: any;
}

declare module 'dugite/jest.fast.config' {
  declare module.exports: any;
}

declare module 'dugite/jest.slow.config' {
  declare module.exports: any;
}

declare module 'dugite/script/config' {
  declare module.exports: any;
}

declare module 'dugite/script/download-git' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dugite/build/lib/errors.js' {
  declare module.exports: $Exports<'dugite/build/lib/errors'>;
}
declare module 'dugite/build/lib/git-environment.js' {
  declare module.exports: $Exports<'dugite/build/lib/git-environment'>;
}
declare module 'dugite/build/lib/git-process.js' {
  declare module.exports: $Exports<'dugite/build/lib/git-process'>;
}
declare module 'dugite/build/lib/index' {
  declare module.exports: $Exports<'dugite/build/lib'>;
}
declare module 'dugite/build/lib/index.js' {
  declare module.exports: $Exports<'dugite/build/lib'>;
}
declare module 'dugite/jest.external.config.js' {
  declare module.exports: $Exports<'dugite/jest.external.config'>;
}
declare module 'dugite/jest.fast.config.js' {
  declare module.exports: $Exports<'dugite/jest.fast.config'>;
}
declare module 'dugite/jest.slow.config.js' {
  declare module.exports: $Exports<'dugite/jest.slow.config'>;
}
declare module 'dugite/script/config.js' {
  declare module.exports: $Exports<'dugite/script/config'>;
}
declare module 'dugite/script/download-git.js' {
  declare module.exports: $Exports<'dugite/script/download-git'>;
}
