// flow-typed signature: a0616d516ddc52407969076e842852ba
// flow-typed version: <<STUB>>/electron-notarize_v1.0.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-notarize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-notarize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-notarize/lib/helpers' {
  declare module.exports: any;
}

declare module 'electron-notarize/lib' {
  declare module.exports: any;
}

declare module 'electron-notarize/lib/spawn' {
  declare module.exports: any;
}

declare module 'electron-notarize/lib/validate-args' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-notarize/lib/helpers.js' {
  declare module.exports: $Exports<'electron-notarize/lib/helpers'>;
}
declare module 'electron-notarize/lib/index' {
  declare module.exports: $Exports<'electron-notarize/lib'>;
}
declare module 'electron-notarize/lib/index.js' {
  declare module.exports: $Exports<'electron-notarize/lib'>;
}
declare module 'electron-notarize/lib/spawn.js' {
  declare module.exports: $Exports<'electron-notarize/lib/spawn'>;
}
declare module 'electron-notarize/lib/validate-args.js' {
  declare module.exports: $Exports<'electron-notarize/lib/validate-args'>;
}
