// flow-typed signature: aa0d4bcba81421253d33c698f6347ad0
// flow-typed version: <<STUB>>/electron-settings_v3.2.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-settings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-settings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-settings/lib/settings-helpers' {
  declare module.exports: any;
}

declare module 'electron-settings/lib/settings-observer' {
  declare module.exports: any;
}

declare module 'electron-settings/lib/settings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-settings/index' {
  declare module.exports: $Exports<'electron-settings'>;
}
declare module 'electron-settings/index.js' {
  declare module.exports: $Exports<'electron-settings'>;
}
declare module 'electron-settings/lib/settings-helpers.js' {
  declare module.exports: $Exports<'electron-settings/lib/settings-helpers'>;
}
declare module 'electron-settings/lib/settings-observer.js' {
  declare module.exports: $Exports<'electron-settings/lib/settings-observer'>;
}
declare module 'electron-settings/lib/settings.js' {
  declare module.exports: $Exports<'electron-settings/lib/settings'>;
}
