// flow-typed signature: dec52d053933b1beb3afcea209b26c2d
// flow-typed version: <<STUB>>/electron-settings_v4.0.2/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-settings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-settings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-settings/dist/settings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-settings/dist/settings.js' {
  declare module.exports: $Exports<'electron-settings/dist/settings'>;
}
