// flow-typed signature: 70e8296e3ab5b38cad515ab75b8b7ddf
// flow-typed version: <<STUB>>/eslint-plugin-sonarjs_v0.5.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-sonarjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-sonarjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-sonarjs/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/cognitive-complexity' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/max-switch-cases' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-all-duplicated-branches' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-collapsible-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-collection-size-mischeck' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-duplicate-string' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-duplicated-branches' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-element-overwrite' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-extra-arguments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-identical-conditions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-identical-expressions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-identical-functions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-inverted-boolean-check' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-one-iteration-loop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-redundant-boolean' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-redundant-jump' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-same-line-conditional' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-small-switch' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-unused-collection' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-use-of-empty-return-value' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/no-useless-catch' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/prefer-immediate-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/prefer-object-literal' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/prefer-single-boolean-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/rules/prefer-while' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/utils/collections' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/utils/conditions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/utils/equivalence' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/utils/locations' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/utils/nodes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sonarjs/lib/utils/parser-services' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-sonarjs/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib'>;
}
declare module 'eslint-plugin-sonarjs/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/cognitive-complexity.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/cognitive-complexity'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/max-switch-cases.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/max-switch-cases'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-all-duplicated-branches.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-all-duplicated-branches'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-collapsible-if.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-collapsible-if'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-collection-size-mischeck.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-collection-size-mischeck'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-duplicate-string.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-duplicate-string'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-duplicated-branches.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-duplicated-branches'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-element-overwrite.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-element-overwrite'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-extra-arguments.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-extra-arguments'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-identical-conditions.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-identical-conditions'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-identical-expressions.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-identical-expressions'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-identical-functions.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-identical-functions'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-inverted-boolean-check.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-inverted-boolean-check'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-one-iteration-loop.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-one-iteration-loop'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-redundant-boolean.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-redundant-boolean'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-redundant-jump.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-redundant-jump'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-same-line-conditional.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-same-line-conditional'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-small-switch.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-small-switch'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-unused-collection.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-unused-collection'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-use-of-empty-return-value.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-use-of-empty-return-value'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/no-useless-catch.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/no-useless-catch'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/prefer-immediate-return.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/prefer-immediate-return'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/prefer-object-literal.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/prefer-object-literal'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/prefer-single-boolean-return.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/prefer-single-boolean-return'>;
}
declare module 'eslint-plugin-sonarjs/lib/rules/prefer-while.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/rules/prefer-while'>;
}
declare module 'eslint-plugin-sonarjs/lib/utils/collections.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/utils/collections'>;
}
declare module 'eslint-plugin-sonarjs/lib/utils/conditions.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/utils/conditions'>;
}
declare module 'eslint-plugin-sonarjs/lib/utils/equivalence.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/utils/equivalence'>;
}
declare module 'eslint-plugin-sonarjs/lib/utils/locations.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/utils/locations'>;
}
declare module 'eslint-plugin-sonarjs/lib/utils/nodes.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/utils/nodes'>;
}
declare module 'eslint-plugin-sonarjs/lib/utils/parser-services.js' {
  declare module.exports: $Exports<'eslint-plugin-sonarjs/lib/utils/parser-services'>;
}
