// flow-typed signature: bf14c4b4c3b4bd5e23c8e32f7e7a4274
// flow-typed version: <<STUB>>/eslint-plugin-react-hooks_v4.1.2/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development.js' {
  declare module.exports: $Exports<'eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development'>;
}
declare module 'eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.production.min.js' {
  declare module.exports: $Exports<'eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.production.min'>;
}
declare module 'eslint-plugin-react-hooks/index' {
  declare module.exports: $Exports<'eslint-plugin-react-hooks'>;
}
declare module 'eslint-plugin-react-hooks/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-hooks'>;
}
