// flow-typed signature: 4ba52d072057fe4cd5e442bf124bd001
// flow-typed version: <<STUB>>/follow-redirects_v1.11.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'follow-redirects'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'follow-redirects' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'follow-redirects/http' {
  declare module.exports: any;
}

declare module 'follow-redirects/https' {
  declare module.exports: any;
}

// Filename aliases
declare module 'follow-redirects/http.js' {
  declare module.exports: $Exports<'follow-redirects/http'>;
}
declare module 'follow-redirects/https.js' {
  declare module.exports: $Exports<'follow-redirects/https'>;
}
declare module 'follow-redirects/index' {
  declare module.exports: $Exports<'follow-redirects'>;
}
declare module 'follow-redirects/index.js' {
  declare module.exports: $Exports<'follow-redirects'>;
}
