// flow-typed signature: c1451e0b869c3ce35774c4f6a9364132
// flow-typed version: <<STUB>>/graphql-hooks_v4.5.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-hooks/dist/graphql-hooks' {
  declare module.exports: any;
}

declare module 'graphql-hooks/dist/graphql-hooks.min' {
  declare module.exports: any;
}

declare module 'graphql-hooks/es/graphql-hooks' {
  declare module.exports: any;
}

declare module 'graphql-hooks/lib/graphql-hooks' {
  declare module.exports: any;
}

declare module 'graphql-hooks/src/ClientContext' {
  declare module.exports: any;
}

declare module 'graphql-hooks/src/GraphQLClient' {
  declare module.exports: any;
}

declare module 'graphql-hooks/src' {
  declare module.exports: any;
}

declare module 'graphql-hooks/src/isExtractableFileEnhanced' {
  declare module.exports: any;
}

declare module 'graphql-hooks/src/useClientRequest' {
  declare module.exports: any;
}

declare module 'graphql-hooks/src/useQuery' {
  declare module.exports: any;
}

declare module 'graphql-hooks/src/useSubscription' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-hooks/dist/graphql-hooks.js' {
  declare module.exports: $Exports<'graphql-hooks/dist/graphql-hooks'>;
}
declare module 'graphql-hooks/dist/graphql-hooks.min.js' {
  declare module.exports: $Exports<'graphql-hooks/dist/graphql-hooks.min'>;
}
declare module 'graphql-hooks/es/graphql-hooks.js' {
  declare module.exports: $Exports<'graphql-hooks/es/graphql-hooks'>;
}
declare module 'graphql-hooks/lib/graphql-hooks.js' {
  declare module.exports: $Exports<'graphql-hooks/lib/graphql-hooks'>;
}
declare module 'graphql-hooks/src/ClientContext.js' {
  declare module.exports: $Exports<'graphql-hooks/src/ClientContext'>;
}
declare module 'graphql-hooks/src/GraphQLClient.js' {
  declare module.exports: $Exports<'graphql-hooks/src/GraphQLClient'>;
}
declare module 'graphql-hooks/src/index' {
  declare module.exports: $Exports<'graphql-hooks/src'>;
}
declare module 'graphql-hooks/src/index.js' {
  declare module.exports: $Exports<'graphql-hooks/src'>;
}
declare module 'graphql-hooks/src/isExtractableFileEnhanced.js' {
  declare module.exports: $Exports<'graphql-hooks/src/isExtractableFileEnhanced'>;
}
declare module 'graphql-hooks/src/useClientRequest.js' {
  declare module.exports: $Exports<'graphql-hooks/src/useClientRequest'>;
}
declare module 'graphql-hooks/src/useQuery.js' {
  declare module.exports: $Exports<'graphql-hooks/src/useQuery'>;
}
declare module 'graphql-hooks/src/useSubscription.js' {
  declare module.exports: $Exports<'graphql-hooks/src/useSubscription'>;
}
