// flow-typed signature: 1743cc796276fb60480f35d5267d16fe
// flow-typed version: <<STUB>>/i18next-fs-backend_v^1.0.7/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-fs-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-fs-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-fs-backend/cjs/extname' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/cjs/formats/json5' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/cjs/formats/yaml' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/cjs/fs' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/cjs' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/cjs/readFile' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/cjs/utils' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/cjs/writeFile' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/esm/extname' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/esm/formats/json5' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/esm/formats/yaml' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/esm' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/esm/readFile' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/esm/utils' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/esm/writeFile' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/lib/extname' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/lib/formats/json5' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/lib/formats/yaml' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/lib' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/lib/readFile' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/lib/utils' {
  declare module.exports: any;
}

declare module 'i18next-fs-backend/lib/writeFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-fs-backend/cjs/extname.js' {
  declare module.exports: $Exports<'i18next-fs-backend/cjs/extname'>;
}
declare module 'i18next-fs-backend/cjs/formats/json5.js' {
  declare module.exports: $Exports<'i18next-fs-backend/cjs/formats/json5'>;
}
declare module 'i18next-fs-backend/cjs/formats/yaml.js' {
  declare module.exports: $Exports<'i18next-fs-backend/cjs/formats/yaml'>;
}
declare module 'i18next-fs-backend/cjs/fs.js' {
  declare module.exports: $Exports<'i18next-fs-backend/cjs/fs'>;
}
declare module 'i18next-fs-backend/cjs/index' {
  declare module.exports: $Exports<'i18next-fs-backend/cjs'>;
}
declare module 'i18next-fs-backend/cjs/index.js' {
  declare module.exports: $Exports<'i18next-fs-backend/cjs'>;
}
declare module 'i18next-fs-backend/cjs/readFile.js' {
  declare module.exports: $Exports<'i18next-fs-backend/cjs/readFile'>;
}
declare module 'i18next-fs-backend/cjs/utils.js' {
  declare module.exports: $Exports<'i18next-fs-backend/cjs/utils'>;
}
declare module 'i18next-fs-backend/cjs/writeFile.js' {
  declare module.exports: $Exports<'i18next-fs-backend/cjs/writeFile'>;
}
declare module 'i18next-fs-backend/esm/extname.js' {
  declare module.exports: $Exports<'i18next-fs-backend/esm/extname'>;
}
declare module 'i18next-fs-backend/esm/formats/json5.js' {
  declare module.exports: $Exports<'i18next-fs-backend/esm/formats/json5'>;
}
declare module 'i18next-fs-backend/esm/formats/yaml.js' {
  declare module.exports: $Exports<'i18next-fs-backend/esm/formats/yaml'>;
}
declare module 'i18next-fs-backend/esm/index' {
  declare module.exports: $Exports<'i18next-fs-backend/esm'>;
}
declare module 'i18next-fs-backend/esm/index.js' {
  declare module.exports: $Exports<'i18next-fs-backend/esm'>;
}
declare module 'i18next-fs-backend/esm/readFile.js' {
  declare module.exports: $Exports<'i18next-fs-backend/esm/readFile'>;
}
declare module 'i18next-fs-backend/esm/utils.js' {
  declare module.exports: $Exports<'i18next-fs-backend/esm/utils'>;
}
declare module 'i18next-fs-backend/esm/writeFile.js' {
  declare module.exports: $Exports<'i18next-fs-backend/esm/writeFile'>;
}
declare module 'i18next-fs-backend/index' {
  declare module.exports: $Exports<'i18next-fs-backend'>;
}
declare module 'i18next-fs-backend/index.js' {
  declare module.exports: $Exports<'i18next-fs-backend'>;
}
declare module 'i18next-fs-backend/lib/extname.js' {
  declare module.exports: $Exports<'i18next-fs-backend/lib/extname'>;
}
declare module 'i18next-fs-backend/lib/formats/json5.js' {
  declare module.exports: $Exports<'i18next-fs-backend/lib/formats/json5'>;
}
declare module 'i18next-fs-backend/lib/formats/yaml.js' {
  declare module.exports: $Exports<'i18next-fs-backend/lib/formats/yaml'>;
}
declare module 'i18next-fs-backend/lib/index' {
  declare module.exports: $Exports<'i18next-fs-backend/lib'>;
}
declare module 'i18next-fs-backend/lib/index.js' {
  declare module.exports: $Exports<'i18next-fs-backend/lib'>;
}
declare module 'i18next-fs-backend/lib/readFile.js' {
  declare module.exports: $Exports<'i18next-fs-backend/lib/readFile'>;
}
declare module 'i18next-fs-backend/lib/utils.js' {
  declare module.exports: $Exports<'i18next-fs-backend/lib/utils'>;
}
declare module 'i18next-fs-backend/lib/writeFile.js' {
  declare module.exports: $Exports<'i18next-fs-backend/lib/writeFile'>;
}
