// flow-typed signature: 4384fe04a50d7d20931d715ada283464
// flow-typed version: <<STUB>>/i18next_v^19.8.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next/dist/cjs/i18next' {
  declare module.exports: any;
}

declare module 'i18next/dist/esm/i18next' {
  declare module.exports: any;
}

declare module 'i18next/dist/umd/i18next' {
  declare module.exports: any;
}

declare module 'i18next/dist/umd/i18next.min' {
  declare module.exports: any;
}

declare module 'i18next/i18next' {
  declare module.exports: any;
}

declare module 'i18next/i18next.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next/dist/cjs/i18next.js' {
  declare module.exports: $Exports<'i18next/dist/cjs/i18next'>;
}
declare module 'i18next/dist/esm/i18next.js' {
  declare module.exports: $Exports<'i18next/dist/esm/i18next'>;
}
declare module 'i18next/dist/umd/i18next.js' {
  declare module.exports: $Exports<'i18next/dist/umd/i18next'>;
}
declare module 'i18next/dist/umd/i18next.min.js' {
  declare module.exports: $Exports<'i18next/dist/umd/i18next.min'>;
}
declare module 'i18next/i18next.js' {
  declare module.exports: $Exports<'i18next/i18next'>;
}
declare module 'i18next/i18next.min.js' {
  declare module.exports: $Exports<'i18next/i18next.min'>;
}
declare module 'i18next/index' {
  declare module.exports: $Exports<'i18next'>;
}
declare module 'i18next/index.js' {
  declare module.exports: $Exports<'i18next'>;
}
