// flow-typed signature: 58de79caf298f569f32bd8e01b5c2a74
// flow-typed version: <<STUB>>/isomorphic-git_v^1.7.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-git'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-git' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-git/cli' {
  declare module.exports: any;
}

declare module 'isomorphic-git/http/node' {
  declare module.exports: any;
}

declare module 'isomorphic-git/http/web' {
  declare module.exports: any;
}

declare module 'isomorphic-git/http/web/index.umd' {
  declare module.exports: any;
}

declare module 'isomorphic-git/index.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-git/cli.js' {
  declare module.exports: $Exports<'isomorphic-git/cli'>;
}
declare module 'isomorphic-git/http/node/index' {
  declare module.exports: $Exports<'isomorphic-git/http/node'>;
}
declare module 'isomorphic-git/http/node/index.js' {
  declare module.exports: $Exports<'isomorphic-git/http/node'>;
}
declare module 'isomorphic-git/http/web/index' {
  declare module.exports: $Exports<'isomorphic-git/http/web'>;
}
declare module 'isomorphic-git/http/web/index.js' {
  declare module.exports: $Exports<'isomorphic-git/http/web'>;
}
declare module 'isomorphic-git/http/web/index.umd.js' {
  declare module.exports: $Exports<'isomorphic-git/http/web/index.umd'>;
}
declare module 'isomorphic-git/index' {
  declare module.exports: $Exports<'isomorphic-git'>;
}
declare module 'isomorphic-git/index.js' {
  declare module.exports: $Exports<'isomorphic-git'>;
}
declare module 'isomorphic-git/index.umd.min.js' {
  declare module.exports: $Exports<'isomorphic-git/index.umd.min'>;
}
