// flow-typed signature: 533b37192a5784a38d5ccef66b6e440f
// flow-typed version: <<STUB>>/jimp_v0.16.1/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jimp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jimp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jimp/browser/examples/jimp-worker' {
  declare module.exports: any;
}

declare module 'jimp/browser/lib/jimp' {
  declare module.exports: any;
}

declare module 'jimp/browser/lib/jimp.min' {
  declare module.exports: any;
}

declare module 'jimp/dist' {
  declare module.exports: any;
}

declare module 'jimp/es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jimp/browser/examples/jimp-worker.js' {
  declare module.exports: $Exports<'jimp/browser/examples/jimp-worker'>;
}
declare module 'jimp/browser/lib/jimp.js' {
  declare module.exports: $Exports<'jimp/browser/lib/jimp'>;
}
declare module 'jimp/browser/lib/jimp.min.js' {
  declare module.exports: $Exports<'jimp/browser/lib/jimp.min'>;
}
declare module 'jimp/dist/index' {
  declare module.exports: $Exports<'jimp/dist'>;
}
declare module 'jimp/dist/index.js' {
  declare module.exports: $Exports<'jimp/dist'>;
}
declare module 'jimp/es/index' {
  declare module.exports: $Exports<'jimp/es'>;
}
declare module 'jimp/es/index.js' {
  declare module.exports: $Exports<'jimp/es'>;
}
