// flow-typed signature: 050e4bd60c333293e2724642de165fff
// flow-typed version: <<STUB>>/menubar_v9.0.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'menubar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'menubar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'menubar/lib/__mocks__/electron' {
  declare module.exports: any;
}

declare module 'menubar/lib' {
  declare module.exports: any;
}

declare module 'menubar/lib/Menubar' {
  declare module.exports: any;
}

declare module 'menubar/lib/Menubar.spec' {
  declare module.exports: any;
}

declare module 'menubar/lib/types' {
  declare module.exports: any;
}

declare module 'menubar/lib/util/cleanOptions' {
  declare module.exports: any;
}

declare module 'menubar/lib/util/cleanOptions.spec' {
  declare module.exports: any;
}

declare module 'menubar/lib/util/getWindowPosition' {
  declare module.exports: any;
}

// Filename aliases
declare module 'menubar/lib/__mocks__/electron.js' {
  declare module.exports: $Exports<'menubar/lib/__mocks__/electron'>;
}
declare module 'menubar/lib/index' {
  declare module.exports: $Exports<'menubar/lib'>;
}
declare module 'menubar/lib/index.js' {
  declare module.exports: $Exports<'menubar/lib'>;
}
declare module 'menubar/lib/Menubar.js' {
  declare module.exports: $Exports<'menubar/lib/Menubar'>;
}
declare module 'menubar/lib/Menubar.spec.js' {
  declare module.exports: $Exports<'menubar/lib/Menubar.spec'>;
}
declare module 'menubar/lib/types.js' {
  declare module.exports: $Exports<'menubar/lib/types'>;
}
declare module 'menubar/lib/util/cleanOptions.js' {
  declare module.exports: $Exports<'menubar/lib/util/cleanOptions'>;
}
declare module 'menubar/lib/util/cleanOptions.spec.js' {
  declare module.exports: $Exports<'menubar/lib/util/cleanOptions.spec'>;
}
declare module 'menubar/lib/util/getWindowPosition.js' {
  declare module.exports: $Exports<'menubar/lib/util/getWindowPosition'>;
}
