// flow-typed signature: cd1c0a4f6d72b24556a29ff6e6b4f868
// flow-typed version: <<STUB>>/patch-package_v6.2.2/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'patch-package'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'patch-package' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'patch-package/dist/applyPatches' {
  declare module.exports: any;
}

declare module 'patch-package/dist/assertNever' {
  declare module.exports: any;
}

declare module 'patch-package/dist/detectPackageManager' {
  declare module.exports: any;
}

declare module 'patch-package/dist/filterFiles' {
  declare module.exports: any;
}

declare module 'patch-package/dist/getAppRootPath' {
  declare module.exports: any;
}

declare module 'patch-package/dist/getPackageResolution' {
  declare module.exports: any;
}

declare module 'patch-package/dist' {
  declare module.exports: any;
}

declare module 'patch-package/dist/makePatch' {
  declare module.exports: any;
}

declare module 'patch-package/dist/makeRegExp' {
  declare module.exports: any;
}

declare module 'patch-package/dist/PackageDetails' {
  declare module.exports: any;
}

declare module 'patch-package/dist/PackageDetails.test' {
  declare module.exports: any;
}

declare module 'patch-package/dist/packageIsDevDependency' {
  declare module.exports: any;
}

declare module 'patch-package/dist/packageIsDevDependency.test' {
  declare module.exports: any;
}

declare module 'patch-package/dist/patch/apply' {
  declare module.exports: any;
}

declare module 'patch-package/dist/patch/parse' {
  declare module.exports: any;
}

declare module 'patch-package/dist/patch/read' {
  declare module.exports: any;
}

declare module 'patch-package/dist/patch/reverse' {
  declare module.exports: any;
}

declare module 'patch-package/dist/patchFs' {
  declare module.exports: any;
}

declare module 'patch-package/dist/path' {
  declare module.exports: any;
}

declare module 'patch-package/dist/resolveRelativeFileDependencies' {
  declare module.exports: any;
}

declare module 'patch-package/dist/resolveRelativeFileDependencies.test' {
  declare module.exports: any;
}

declare module 'patch-package/dist/spawnSafe' {
  declare module.exports: any;
}

// Filename aliases
declare module 'patch-package/dist/applyPatches.js' {
  declare module.exports: $Exports<'patch-package/dist/applyPatches'>;
}
declare module 'patch-package/dist/assertNever.js' {
  declare module.exports: $Exports<'patch-package/dist/assertNever'>;
}
declare module 'patch-package/dist/detectPackageManager.js' {
  declare module.exports: $Exports<'patch-package/dist/detectPackageManager'>;
}
declare module 'patch-package/dist/filterFiles.js' {
  declare module.exports: $Exports<'patch-package/dist/filterFiles'>;
}
declare module 'patch-package/dist/getAppRootPath.js' {
  declare module.exports: $Exports<'patch-package/dist/getAppRootPath'>;
}
declare module 'patch-package/dist/getPackageResolution.js' {
  declare module.exports: $Exports<'patch-package/dist/getPackageResolution'>;
}
declare module 'patch-package/dist/index' {
  declare module.exports: $Exports<'patch-package/dist'>;
}
declare module 'patch-package/dist/index.js' {
  declare module.exports: $Exports<'patch-package/dist'>;
}
declare module 'patch-package/dist/makePatch.js' {
  declare module.exports: $Exports<'patch-package/dist/makePatch'>;
}
declare module 'patch-package/dist/makeRegExp.js' {
  declare module.exports: $Exports<'patch-package/dist/makeRegExp'>;
}
declare module 'patch-package/dist/PackageDetails.js' {
  declare module.exports: $Exports<'patch-package/dist/PackageDetails'>;
}
declare module 'patch-package/dist/PackageDetails.test.js' {
  declare module.exports: $Exports<'patch-package/dist/PackageDetails.test'>;
}
declare module 'patch-package/dist/packageIsDevDependency.js' {
  declare module.exports: $Exports<'patch-package/dist/packageIsDevDependency'>;
}
declare module 'patch-package/dist/packageIsDevDependency.test.js' {
  declare module.exports: $Exports<'patch-package/dist/packageIsDevDependency.test'>;
}
declare module 'patch-package/dist/patch/apply.js' {
  declare module.exports: $Exports<'patch-package/dist/patch/apply'>;
}
declare module 'patch-package/dist/patch/parse.js' {
  declare module.exports: $Exports<'patch-package/dist/patch/parse'>;
}
declare module 'patch-package/dist/patch/read.js' {
  declare module.exports: $Exports<'patch-package/dist/patch/read'>;
}
declare module 'patch-package/dist/patch/reverse.js' {
  declare module.exports: $Exports<'patch-package/dist/patch/reverse'>;
}
declare module 'patch-package/dist/patchFs.js' {
  declare module.exports: $Exports<'patch-package/dist/patchFs'>;
}
declare module 'patch-package/dist/path.js' {
  declare module.exports: $Exports<'patch-package/dist/path'>;
}
declare module 'patch-package/dist/resolveRelativeFileDependencies.js' {
  declare module.exports: $Exports<'patch-package/dist/resolveRelativeFileDependencies'>;
}
declare module 'patch-package/dist/resolveRelativeFileDependencies.test.js' {
  declare module.exports: $Exports<'patch-package/dist/resolveRelativeFileDependencies.test'>;
}
declare module 'patch-package/dist/spawnSafe.js' {
  declare module.exports: $Exports<'patch-package/dist/spawnSafe'>;
}
declare module 'patch-package/index' {
  declare module.exports: $Exports<'patch-package'>;
}
declare module 'patch-package/index.js' {
  declare module.exports: $Exports<'patch-package'>;
}
