// flow-typed signature: a09e676723a6497a38e4cb8c96b7bfa2
// flow-typed version: <<STUB>>/proxy-agent_v4.0.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'proxy-agent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'proxy-agent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'proxy-agent/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'proxy-agent/index' {
  declare module.exports: $Exports<'proxy-agent'>;
}
declare module 'proxy-agent/index.js' {
  declare module.exports: $Exports<'proxy-agent'>;
}
declare module 'proxy-agent/test/test.js' {
  declare module.exports: $Exports<'proxy-agent/test/test'>;
}
