// flow-typed signature: a2e65952744485e836f06892458deb4c
// flow-typed version: <<STUB>>/react-sortable-hoc_v1.11.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sortable-hoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sortable-hoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sortable-hoc/dist/react-sortable-hoc.esm' {
  declare module.exports: any;
}

declare module 'react-sortable-hoc/dist/react-sortable-hoc' {
  declare module.exports: any;
}

declare module 'react-sortable-hoc/dist/react-sortable-hoc.umd' {
  declare module.exports: any;
}

declare module 'react-sortable-hoc/dist/react-sortable-hoc.umd.min' {
  declare module.exports: any;
}

declare module 'react-sortable-hoc/examples/basic' {
  declare module.exports: any;
}

declare module 'react-sortable-hoc/examples/collections' {
  declare module.exports: any;
}

declare module 'react-sortable-hoc/examples/drag-handle' {
  declare module.exports: any;
}

declare module 'react-sortable-hoc/examples/react-infinite' {
  declare module.exports: any;
}

declare module 'react-sortable-hoc/examples/react-virtualized-table-columns' {
  declare module.exports: any;
}

declare module 'react-sortable-hoc/examples/react-virtualized' {
  declare module.exports: any;
}

declare module 'react-sortable-hoc/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sortable-hoc/dist/react-sortable-hoc.esm.js' {
  declare module.exports: $Exports<'react-sortable-hoc/dist/react-sortable-hoc.esm'>;
}
declare module 'react-sortable-hoc/dist/react-sortable-hoc.js' {
  declare module.exports: $Exports<'react-sortable-hoc/dist/react-sortable-hoc'>;
}
declare module 'react-sortable-hoc/dist/react-sortable-hoc.umd.js' {
  declare module.exports: $Exports<'react-sortable-hoc/dist/react-sortable-hoc.umd'>;
}
declare module 'react-sortable-hoc/dist/react-sortable-hoc.umd.min.js' {
  declare module.exports: $Exports<'react-sortable-hoc/dist/react-sortable-hoc.umd.min'>;
}
declare module 'react-sortable-hoc/examples/basic.js' {
  declare module.exports: $Exports<'react-sortable-hoc/examples/basic'>;
}
declare module 'react-sortable-hoc/examples/collections.js' {
  declare module.exports: $Exports<'react-sortable-hoc/examples/collections'>;
}
declare module 'react-sortable-hoc/examples/drag-handle.js' {
  declare module.exports: $Exports<'react-sortable-hoc/examples/drag-handle'>;
}
declare module 'react-sortable-hoc/examples/react-infinite.js' {
  declare module.exports: $Exports<'react-sortable-hoc/examples/react-infinite'>;
}
declare module 'react-sortable-hoc/examples/react-virtualized-table-columns.js' {
  declare module.exports: $Exports<'react-sortable-hoc/examples/react-virtualized-table-columns'>;
}
declare module 'react-sortable-hoc/examples/react-virtualized.js' {
  declare module.exports: $Exports<'react-sortable-hoc/examples/react-virtualized'>;
}
declare module 'react-sortable-hoc/rollup.config.js' {
  declare module.exports: $Exports<'react-sortable-hoc/rollup.config'>;
}
