// flow-typed signature: b6b3e679d0a10f9f5be96209de5c4f15
// flow-typed version: <<STUB>>/react-ace_v8.1.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ace/coverage/block-navigation' {
  declare module.exports: any;
}

declare module 'react-ace/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'react-ace/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-ace/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-ace/coverage/prettify' {
  declare module.exports: any;
}

declare module 'react-ace/coverage/sorter' {
  declare module.exports: any;
}

declare module 'react-ace/dist/react-ace' {
  declare module.exports: any;
}

declare module 'react-ace/dist/react-ace.min' {
  declare module.exports: any;
}

declare module 'react-ace/lib/ace' {
  declare module.exports: any;
}

declare module 'react-ace/lib/AceEditorClass' {
  declare module.exports: any;
}

declare module 'react-ace/lib/diff' {
  declare module.exports: any;
}

declare module 'react-ace/lib/editorOptions' {
  declare module.exports: any;
}

declare module 'react-ace/lib' {
  declare module.exports: any;
}

declare module 'react-ace/lib/split' {
  declare module.exports: any;
}

declare module 'react-ace/lib/types' {
  declare module.exports: any;
}

declare module 'react-ace/tests/setup' {
  declare module.exports: any;
}

declare module 'react-ace/tests/src/ace.spec' {
  declare module.exports: any;
}

declare module 'react-ace/tests/src/split.spec' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.base' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.development' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.example' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ace/coverage/block-navigation.js' {
  declare module.exports: $Exports<'react-ace/coverage/block-navigation'>;
}
declare module 'react-ace/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'react-ace/coverage/lcov-report/block-navigation'>;
}
declare module 'react-ace/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-ace/coverage/lcov-report/prettify'>;
}
declare module 'react-ace/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-ace/coverage/lcov-report/sorter'>;
}
declare module 'react-ace/coverage/prettify.js' {
  declare module.exports: $Exports<'react-ace/coverage/prettify'>;
}
declare module 'react-ace/coverage/sorter.js' {
  declare module.exports: $Exports<'react-ace/coverage/sorter'>;
}
declare module 'react-ace/dist/react-ace.js' {
  declare module.exports: $Exports<'react-ace/dist/react-ace'>;
}
declare module 'react-ace/dist/react-ace.min.js' {
  declare module.exports: $Exports<'react-ace/dist/react-ace.min'>;
}
declare module 'react-ace/lib/ace.js' {
  declare module.exports: $Exports<'react-ace/lib/ace'>;
}
declare module 'react-ace/lib/AceEditorClass.js' {
  declare module.exports: $Exports<'react-ace/lib/AceEditorClass'>;
}
declare module 'react-ace/lib/diff.js' {
  declare module.exports: $Exports<'react-ace/lib/diff'>;
}
declare module 'react-ace/lib/editorOptions.js' {
  declare module.exports: $Exports<'react-ace/lib/editorOptions'>;
}
declare module 'react-ace/lib/index' {
  declare module.exports: $Exports<'react-ace/lib'>;
}
declare module 'react-ace/lib/index.js' {
  declare module.exports: $Exports<'react-ace/lib'>;
}
declare module 'react-ace/lib/split.js' {
  declare module.exports: $Exports<'react-ace/lib/split'>;
}
declare module 'react-ace/lib/types.js' {
  declare module.exports: $Exports<'react-ace/lib/types'>;
}
declare module 'react-ace/tests/setup.js' {
  declare module.exports: $Exports<'react-ace/tests/setup'>;
}
declare module 'react-ace/tests/src/ace.spec.js' {
  declare module.exports: $Exports<'react-ace/tests/src/ace.spec'>;
}
declare module 'react-ace/tests/src/split.spec.js' {
  declare module.exports: $Exports<'react-ace/tests/src/split.spec'>;
}
declare module 'react-ace/webpack.config.base.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.base'>;
}
declare module 'react-ace/webpack.config.development.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.development'>;
}
declare module 'react-ace/webpack.config.example.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.example'>;
}
declare module 'react-ace/webpack.config.production.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.production'>;
}
