// flow-typed signature: b3faaf12198e541eb0c20555f4cb4a10
// flow-typed version: <<STUB>>/react-i18next_v^11.7.3/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-i18next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-i18next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-i18next/dist/amd/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/amd/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/context' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/Translation' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/useSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/useTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/utils' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/withSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/withTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/context' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/Translation' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/useSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/useTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/utils' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/withSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/withTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/umd/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/umd/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/icu.macro' {
  declare module.exports: any;
}

declare module 'react-i18next/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/rollup.config' {
  declare module.exports: any;
}

declare module 'react-i18next/src/context' {
  declare module.exports: any;
}

declare module 'react-i18next/src/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/src' {
  declare module.exports: any;
}

declare module 'react-i18next/src/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/src/Translation' {
  declare module.exports: any;
}

declare module 'react-i18next/src/useSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/src/useTranslation' {
  declare module.exports: any;
}

declare module 'react-i18next/src/utils' {
  declare module.exports: any;
}

declare module 'react-i18next/src/withSSR' {
  declare module.exports: any;
}

declare module 'react-i18next/src/withTranslation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-i18next/dist/amd/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/dist/amd/react-i18next'>;
}
declare module 'react-i18next/dist/amd/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/dist/amd/react-i18next.min'>;
}
declare module 'react-i18next/dist/commonjs/context.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/context'>;
}
declare module 'react-i18next/dist/commonjs/I18nextProvider.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/I18nextProvider'>;
}
declare module 'react-i18next/dist/commonjs/index' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs'>;
}
declare module 'react-i18next/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs'>;
}
declare module 'react-i18next/dist/commonjs/Trans.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/Trans'>;
}
declare module 'react-i18next/dist/commonjs/Translation.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/Translation'>;
}
declare module 'react-i18next/dist/commonjs/useSSR.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/useSSR'>;
}
declare module 'react-i18next/dist/commonjs/useTranslation.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/useTranslation'>;
}
declare module 'react-i18next/dist/commonjs/utils.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/utils'>;
}
declare module 'react-i18next/dist/commonjs/withSSR.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/withSSR'>;
}
declare module 'react-i18next/dist/commonjs/withTranslation.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/withTranslation'>;
}
declare module 'react-i18next/dist/es/context.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/context'>;
}
declare module 'react-i18next/dist/es/I18nextProvider.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/I18nextProvider'>;
}
declare module 'react-i18next/dist/es/index' {
  declare module.exports: $Exports<'react-i18next/dist/es'>;
}
declare module 'react-i18next/dist/es/index.js' {
  declare module.exports: $Exports<'react-i18next/dist/es'>;
}
declare module 'react-i18next/dist/es/Trans.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/Trans'>;
}
declare module 'react-i18next/dist/es/Translation.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/Translation'>;
}
declare module 'react-i18next/dist/es/useSSR.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/useSSR'>;
}
declare module 'react-i18next/dist/es/useTranslation.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/useTranslation'>;
}
declare module 'react-i18next/dist/es/utils.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/utils'>;
}
declare module 'react-i18next/dist/es/withSSR.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/withSSR'>;
}
declare module 'react-i18next/dist/es/withTranslation.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/withTranslation'>;
}
declare module 'react-i18next/dist/umd/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/dist/umd/react-i18next'>;
}
declare module 'react-i18next/dist/umd/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/dist/umd/react-i18next.min'>;
}
declare module 'react-i18next/icu.macro.js' {
  declare module.exports: $Exports<'react-i18next/icu.macro'>;
}
declare module 'react-i18next/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/react-i18next'>;
}
declare module 'react-i18next/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/react-i18next.min'>;
}
declare module 'react-i18next/rollup.config.js' {
  declare module.exports: $Exports<'react-i18next/rollup.config'>;
}
declare module 'react-i18next/src/context.js' {
  declare module.exports: $Exports<'react-i18next/src/context'>;
}
declare module 'react-i18next/src/I18nextProvider.js' {
  declare module.exports: $Exports<'react-i18next/src/I18nextProvider'>;
}
declare module 'react-i18next/src/index' {
  declare module.exports: $Exports<'react-i18next/src'>;
}
declare module 'react-i18next/src/index.js' {
  declare module.exports: $Exports<'react-i18next/src'>;
}
declare module 'react-i18next/src/Trans.js' {
  declare module.exports: $Exports<'react-i18next/src/Trans'>;
}
declare module 'react-i18next/src/Translation.js' {
  declare module.exports: $Exports<'react-i18next/src/Translation'>;
}
declare module 'react-i18next/src/useSSR.js' {
  declare module.exports: $Exports<'react-i18next/src/useSSR'>;
}
declare module 'react-i18next/src/useTranslation.js' {
  declare module.exports: $Exports<'react-i18next/src/useTranslation'>;
}
declare module 'react-i18next/src/utils.js' {
  declare module.exports: $Exports<'react-i18next/src/utils'>;
}
declare module 'react-i18next/src/withSSR.js' {
  declare module.exports: $Exports<'react-i18next/src/withSSR'>;
}
declare module 'react-i18next/src/withTranslation.js' {
  declare module.exports: $Exports<'react-i18next/src/withTranslation'>;
}
