// flow-typed signature: 1180ac64c69dc764926a577b681f1daa
// flow-typed version: <<STUB>>/react-window-infinite-loader_v1.0.5/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-window-infinite-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-window-infinite-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-window-infinite-loader/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-window-infinite-loader/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-window-infinite-loader/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-window-infinite-loader/dist/index.cjs'>;
}
declare module 'react-window-infinite-loader/dist/index.esm.js' {
  declare module.exports: $Exports<'react-window-infinite-loader/dist/index.esm'>;
}
