// flow-typed signature: e9b11555ba5f26c2f637c0b4e4b37cd6
// flow-typed version: <<STUB>>/react-scripts_v3.4.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scripts/bin/react-scripts' {
  declare module.exports: any;
}

declare module 'react-scripts/config/env' {
  declare module.exports: any;
}

declare module 'react-scripts/config/getHttpsConfig' {
  declare module.exports: any;
}

declare module 'react-scripts/config/jest/babelTransform' {
  declare module.exports: any;
}

declare module 'react-scripts/config/jest/cssTransform' {
  declare module.exports: any;
}

declare module 'react-scripts/config/jest/fileTransform' {
  declare module.exports: any;
}

declare module 'react-scripts/config/modules' {
  declare module.exports: any;
}

declare module 'react-scripts/config/paths' {
  declare module.exports: any;
}

declare module 'react-scripts/config/pnpTs' {
  declare module.exports: any;
}

declare module 'react-scripts/config/webpack.config' {
  declare module.exports: any;
}

declare module 'react-scripts/config/webpackDevServer.config' {
  declare module.exports: any;
}

declare module 'react-scripts/scripts/build' {
  declare module.exports: any;
}

declare module 'react-scripts/scripts/eject' {
  declare module.exports: any;
}

declare module 'react-scripts/scripts/init' {
  declare module.exports: any;
}

declare module 'react-scripts/scripts/start' {
  declare module.exports: any;
}

declare module 'react-scripts/scripts/test' {
  declare module.exports: any;
}

declare module 'react-scripts/scripts/utils/createJestConfig' {
  declare module.exports: any;
}

declare module 'react-scripts/scripts/utils/verifyPackageTree' {
  declare module.exports: any;
}

declare module 'react-scripts/scripts/utils/verifyTypeScriptSetup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scripts/bin/react-scripts.js' {
  declare module.exports: $Exports<'react-scripts/bin/react-scripts'>;
}
declare module 'react-scripts/config/env.js' {
  declare module.exports: $Exports<'react-scripts/config/env'>;
}
declare module 'react-scripts/config/getHttpsConfig.js' {
  declare module.exports: $Exports<'react-scripts/config/getHttpsConfig'>;
}
declare module 'react-scripts/config/jest/babelTransform.js' {
  declare module.exports: $Exports<'react-scripts/config/jest/babelTransform'>;
}
declare module 'react-scripts/config/jest/cssTransform.js' {
  declare module.exports: $Exports<'react-scripts/config/jest/cssTransform'>;
}
declare module 'react-scripts/config/jest/fileTransform.js' {
  declare module.exports: $Exports<'react-scripts/config/jest/fileTransform'>;
}
declare module 'react-scripts/config/modules.js' {
  declare module.exports: $Exports<'react-scripts/config/modules'>;
}
declare module 'react-scripts/config/paths.js' {
  declare module.exports: $Exports<'react-scripts/config/paths'>;
}
declare module 'react-scripts/config/pnpTs.js' {
  declare module.exports: $Exports<'react-scripts/config/pnpTs'>;
}
declare module 'react-scripts/config/webpack.config.js' {
  declare module.exports: $Exports<'react-scripts/config/webpack.config'>;
}
declare module 'react-scripts/config/webpackDevServer.config.js' {
  declare module.exports: $Exports<'react-scripts/config/webpackDevServer.config'>;
}
declare module 'react-scripts/scripts/build.js' {
  declare module.exports: $Exports<'react-scripts/scripts/build'>;
}
declare module 'react-scripts/scripts/eject.js' {
  declare module.exports: $Exports<'react-scripts/scripts/eject'>;
}
declare module 'react-scripts/scripts/init.js' {
  declare module.exports: $Exports<'react-scripts/scripts/init'>;
}
declare module 'react-scripts/scripts/start.js' {
  declare module.exports: $Exports<'react-scripts/scripts/start'>;
}
declare module 'react-scripts/scripts/test.js' {
  declare module.exports: $Exports<'react-scripts/scripts/test'>;
}
declare module 'react-scripts/scripts/utils/createJestConfig.js' {
  declare module.exports: $Exports<'react-scripts/scripts/utils/createJestConfig'>;
}
declare module 'react-scripts/scripts/utils/verifyPackageTree.js' {
  declare module.exports: $Exports<'react-scripts/scripts/utils/verifyPackageTree'>;
}
declare module 'react-scripts/scripts/utils/verifyTypeScriptSetup.js' {
  declare module.exports: $Exports<'react-scripts/scripts/utils/verifyTypeScriptSetup'>;
}
