// flow-typed signature: 5059e676263a4dd98d80eb2f9753180c
// flow-typed version: <<STUB>>/react-ace_v9.1.3/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ace/dist/react-ace' {
  declare module.exports: any;
}

declare module 'react-ace/dist/react-ace.min' {
  declare module.exports: any;
}

declare module 'react-ace/lib/ace' {
  declare module.exports: any;
}

declare module 'react-ace/lib/diff' {
  declare module.exports: any;
}

declare module 'react-ace/lib/editorOptions' {
  declare module.exports: any;
}

declare module 'react-ace/lib' {
  declare module.exports: any;
}

declare module 'react-ace/lib/split' {
  declare module.exports: any;
}

declare module 'react-ace/lib/types' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.base' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.development' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.example' {
  declare module.exports: any;
}

declare module 'react-ace/webpack.config.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ace/dist/react-ace.js' {
  declare module.exports: $Exports<'react-ace/dist/react-ace'>;
}
declare module 'react-ace/dist/react-ace.min.js' {
  declare module.exports: $Exports<'react-ace/dist/react-ace.min'>;
}
declare module 'react-ace/lib/ace.js' {
  declare module.exports: $Exports<'react-ace/lib/ace'>;
}
declare module 'react-ace/lib/diff.js' {
  declare module.exports: $Exports<'react-ace/lib/diff'>;
}
declare module 'react-ace/lib/editorOptions.js' {
  declare module.exports: $Exports<'react-ace/lib/editorOptions'>;
}
declare module 'react-ace/lib/index' {
  declare module.exports: $Exports<'react-ace/lib'>;
}
declare module 'react-ace/lib/index.js' {
  declare module.exports: $Exports<'react-ace/lib'>;
}
declare module 'react-ace/lib/split.js' {
  declare module.exports: $Exports<'react-ace/lib/split'>;
}
declare module 'react-ace/lib/types.js' {
  declare module.exports: $Exports<'react-ace/lib/types'>;
}
declare module 'react-ace/webpack.config.base.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.base'>;
}
declare module 'react-ace/webpack.config.development.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.development'>;
}
declare module 'react-ace/webpack.config.example.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.example'>;
}
declare module 'react-ace/webpack.config.production.js' {
  declare module.exports: $Exports<'react-ace/webpack.config.production'>;
}
