// flow-typed signature: 59b971109cd240c81f17a8c14befad53
// flow-typed version: <<STUB>>/regedit_v3.0.3/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'regedit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'regedit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'regedit/errors' {
  declare module.exports: any;
}

declare module 'regedit/lib/cscript' {
  declare module.exports: any;
}

declare module 'regedit/lib/execFile' {
  declare module.exports: any;
}

declare module 'regedit/lib/helper' {
  declare module.exports: any;
}

declare module 'regedit/test/benchmarks.test' {
  declare module.exports: any;
}

declare module 'regedit/test/cscript.test' {
  declare module.exports: any;
}

declare module 'regedit/test/execFile.test' {
  declare module.exports: any;
}

declare module 'regedit/test/issues.test' {
  declare module.exports: any;
}

declare module 'regedit/test/jsonSafe.test' {
  declare module.exports: any;
}

declare module 'regedit/test/lib/testscript' {
  declare module.exports: any;
}

declare module 'regedit/test/list.stream.test' {
  declare module.exports: any;
}

declare module 'regedit/test/regedit.test' {
  declare module.exports: any;
}

declare module 'regedit/winerrors/generatedErrorObjects' {
  declare module.exports: any;
}

declare module 'regedit/winerrors/generateErrorDeclaration' {
  declare module.exports: any;
}

declare module 'regedit/winerrors/generateErrorsJS' {
  declare module.exports: any;
}

declare module 'regedit/winerrors/parseErrors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'regedit/errors.js' {
  declare module.exports: $Exports<'regedit/errors'>;
}
declare module 'regedit/index' {
  declare module.exports: $Exports<'regedit'>;
}
declare module 'regedit/index.js' {
  declare module.exports: $Exports<'regedit'>;
}
declare module 'regedit/lib/cscript.js' {
  declare module.exports: $Exports<'regedit/lib/cscript'>;
}
declare module 'regedit/lib/execFile.js' {
  declare module.exports: $Exports<'regedit/lib/execFile'>;
}
declare module 'regedit/lib/helper.js' {
  declare module.exports: $Exports<'regedit/lib/helper'>;
}
declare module 'regedit/test/benchmarks.test.js' {
  declare module.exports: $Exports<'regedit/test/benchmarks.test'>;
}
declare module 'regedit/test/cscript.test.js' {
  declare module.exports: $Exports<'regedit/test/cscript.test'>;
}
declare module 'regedit/test/execFile.test.js' {
  declare module.exports: $Exports<'regedit/test/execFile.test'>;
}
declare module 'regedit/test/issues.test.js' {
  declare module.exports: $Exports<'regedit/test/issues.test'>;
}
declare module 'regedit/test/jsonSafe.test.js' {
  declare module.exports: $Exports<'regedit/test/jsonSafe.test'>;
}
declare module 'regedit/test/lib/testscript.js' {
  declare module.exports: $Exports<'regedit/test/lib/testscript'>;
}
declare module 'regedit/test/list.stream.test.js' {
  declare module.exports: $Exports<'regedit/test/list.stream.test'>;
}
declare module 'regedit/test/regedit.test.js' {
  declare module.exports: $Exports<'regedit/test/regedit.test'>;
}
declare module 'regedit/winerrors/generatedErrorObjects.js' {
  declare module.exports: $Exports<'regedit/winerrors/generatedErrorObjects'>;
}
declare module 'regedit/winerrors/generateErrorDeclaration.js' {
  declare module.exports: $Exports<'regedit/winerrors/generateErrorDeclaration'>;
}
declare module 'regedit/winerrors/generateErrorsJS.js' {
  declare module.exports: $Exports<'regedit/winerrors/generateErrorsJS'>;
}
declare module 'regedit/winerrors/parseErrors.js' {
  declare module.exports: $Exports<'regedit/winerrors/parseErrors'>;
}
