// flow-typed signature: e46ec7057c732cbaa637ed91833d189a
// flow-typed version: <<STUB>>/rescript-disable-eslint_v1.0.2/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rescript-disable-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rescript-disable-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rescript-disable-eslint/dist/rescript-disable-eslint' {
  declare module.exports: any;
}

declare module 'rescript-disable-eslint/dist/rescript-disable-eslint.modern' {
  declare module.exports: any;
}

declare module 'rescript-disable-eslint/dist/rescript-disable-eslint.umd' {
  declare module.exports: any;
}

declare module 'rescript-disable-eslint/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rescript-disable-eslint/dist/rescript-disable-eslint.js' {
  declare module.exports: $Exports<'rescript-disable-eslint/dist/rescript-disable-eslint'>;
}
declare module 'rescript-disable-eslint/dist/rescript-disable-eslint.modern.js' {
  declare module.exports: $Exports<'rescript-disable-eslint/dist/rescript-disable-eslint.modern'>;
}
declare module 'rescript-disable-eslint/dist/rescript-disable-eslint.umd.js' {
  declare module.exports: $Exports<'rescript-disable-eslint/dist/rescript-disable-eslint.umd'>;
}
declare module 'rescript-disable-eslint/src/index' {
  declare module.exports: $Exports<'rescript-disable-eslint/src'>;
}
declare module 'rescript-disable-eslint/src/index.js' {
  declare module.exports: $Exports<'rescript-disable-eslint/src'>;
}
