// flow-typed signature: d99dc6960b6e0b668f54570ac374fdbd
// flow-typed version: <<STUB>>/simplebar_v5.2.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simplebar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simplebar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simplebar/dist/simplebar-core.esm' {
  declare module.exports: any;
}

declare module 'simplebar/dist/simplebar.esm' {
  declare module.exports: any;
}

declare module 'simplebar/dist/simplebar' {
  declare module.exports: any;
}

declare module 'simplebar/dist/simplebar.min' {
  declare module.exports: any;
}

declare module 'simplebar/src/helpers' {
  declare module.exports: any;
}

declare module 'simplebar/src' {
  declare module.exports: any;
}

declare module 'simplebar/src/scrollbar-width' {
  declare module.exports: any;
}

declare module 'simplebar/src/simplebar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simplebar/dist/simplebar-core.esm.js' {
  declare module.exports: $Exports<'simplebar/dist/simplebar-core.esm'>;
}
declare module 'simplebar/dist/simplebar.esm.js' {
  declare module.exports: $Exports<'simplebar/dist/simplebar.esm'>;
}
declare module 'simplebar/dist/simplebar.js' {
  declare module.exports: $Exports<'simplebar/dist/simplebar'>;
}
declare module 'simplebar/dist/simplebar.min.js' {
  declare module.exports: $Exports<'simplebar/dist/simplebar.min'>;
}
declare module 'simplebar/src/helpers.js' {
  declare module.exports: $Exports<'simplebar/src/helpers'>;
}
declare module 'simplebar/src/index' {
  declare module.exports: $Exports<'simplebar/src'>;
}
declare module 'simplebar/src/index.js' {
  declare module.exports: $Exports<'simplebar/src'>;
}
declare module 'simplebar/src/scrollbar-width.js' {
  declare module.exports: $Exports<'simplebar/src/scrollbar-width'>;
}
declare module 'simplebar/src/simplebar.js' {
  declare module.exports: $Exports<'simplebar/src/simplebar'>;
}
