// flow-typed signature: 8b7634e2e0c3cc67be1c6678b712a169
// flow-typed version: <<STUB>>/simplebar-react_v2.2.1/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simplebar-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simplebar-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simplebar-react/dist/simplebar-react.esm' {
  declare module.exports: any;
}

declare module 'simplebar-react/dist/simplebar-react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simplebar-react/dist/simplebar-react.esm.js' {
  declare module.exports: $Exports<'simplebar-react/dist/simplebar-react.esm'>;
}
declare module 'simplebar-react/dist/simplebar-react.js' {
  declare module.exports: $Exports<'simplebar-react/dist/simplebar-react'>;
}
