// flow-typed signature: 8d202554fb93b6b524f240ffb4dd839a
// flow-typed version: <<STUB>>/styled-is_v1.3.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-is'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-is' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-is/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'styled-is/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'styled-is/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'styled-is/dist/styled-is.es' {
  declare module.exports: any;
}

declare module 'styled-is/dist/styled-is.iife' {
  declare module.exports: any;
}

declare module 'styled-is/dist/styled-is.umd' {
  declare module.exports: any;
}

declare module 'styled-is/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-is/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'styled-is/coverage/lcov-report/block-navigation'>;
}
declare module 'styled-is/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'styled-is/coverage/lcov-report/prettify'>;
}
declare module 'styled-is/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'styled-is/coverage/lcov-report/sorter'>;
}
declare module 'styled-is/dist/styled-is.es.js' {
  declare module.exports: $Exports<'styled-is/dist/styled-is.es'>;
}
declare module 'styled-is/dist/styled-is.iife.js' {
  declare module.exports: $Exports<'styled-is/dist/styled-is.iife'>;
}
declare module 'styled-is/dist/styled-is.umd.js' {
  declare module.exports: $Exports<'styled-is/dist/styled-is.umd'>;
}
declare module 'styled-is/test/index' {
  declare module.exports: $Exports<'styled-is/test'>;
}
declare module 'styled-is/test/index.js' {
  declare module.exports: $Exports<'styled-is/test'>;
}
