// flow-typed signature: 13f75fce2df29e7378207528d7c06652
// flow-typed version: <<STUB>>/typeface-roboto_v0.0.75/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
