// flow-typed signature: 74baf179750bd624a6c35032c121ba93
// flow-typed version: <<STUB>>/typeface-roboto_v1.1.13/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
