// flow-typed signature: 944a235b0ea6fe13e053ab992913e06f
// flow-typed version: <<STUB>>/wait-on_v5.1.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wait-on'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wait-on' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wait-on/exampleConfig' {
  declare module.exports: any;
}

declare module 'wait-on/lib/wait-on' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wait-on/exampleConfig.js' {
  declare module.exports: $Exports<'wait-on/exampleConfig'>;
}
declare module 'wait-on/lib/wait-on.js' {
  declare module.exports: $Exports<'wait-on/lib/wait-on'>;
}
