// flow-typed signature: 5b5afca2b6fc07ad8dab037c37c245b6
// flow-typed version: <<STUB>>/winston-transport_v^4.4.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-transport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-transport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-transport/dist' {
  declare module.exports: any;
}

declare module 'winston-transport/dist/legacy' {
  declare module.exports: any;
}

declare module 'winston-transport/legacy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-transport/dist/index' {
  declare module.exports: $Exports<'winston-transport/dist'>;
}
declare module 'winston-transport/dist/index.js' {
  declare module.exports: $Exports<'winston-transport/dist'>;
}
declare module 'winston-transport/dist/legacy.js' {
  declare module.exports: $Exports<'winston-transport/dist/legacy'>;
}
declare module 'winston-transport/index' {
  declare module.exports: $Exports<'winston-transport'>;
}
declare module 'winston-transport/index.js' {
  declare module.exports: $Exports<'winston-transport'>;
}
declare module 'winston-transport/legacy.js' {
  declare module.exports: $Exports<'winston-transport/legacy'>;
}
