// flow-typed signature: a9036a705153ee3821bba0308b9ab76d
// flow-typed version: <<STUB>>/winston-daily-rotate-file_v^4.5.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-daily-rotate-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-daily-rotate-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-daily-rotate-file/daily-rotate-file' {
  declare module.exports: any;
}

declare module 'winston-daily-rotate-file/test/memory-stream' {
  declare module.exports: any;
}

declare module 'winston-daily-rotate-file/test/random-string' {
  declare module.exports: any;
}

declare module 'winston-daily-rotate-file/test/transport-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-daily-rotate-file/daily-rotate-file.js' {
  declare module.exports: $Exports<'winston-daily-rotate-file/daily-rotate-file'>;
}
declare module 'winston-daily-rotate-file/index' {
  declare module.exports: $Exports<'winston-daily-rotate-file'>;
}
declare module 'winston-daily-rotate-file/index.js' {
  declare module.exports: $Exports<'winston-daily-rotate-file'>;
}
declare module 'winston-daily-rotate-file/test/memory-stream.js' {
  declare module.exports: $Exports<'winston-daily-rotate-file/test/memory-stream'>;
}
declare module 'winston-daily-rotate-file/test/random-string.js' {
  declare module.exports: $Exports<'winston-daily-rotate-file/test/random-string'>;
}
declare module 'winston-daily-rotate-file/test/transport-tests.js' {
  declare module.exports: $Exports<'winston-daily-rotate-file/test/transport-tests'>;
}
