// flow-typed signature: 7af3cc7458462f5b54be0db7dab4198b
// flow-typed version: <<STUB>>/@material-ui/lab_v^4.0.0-alpha.56/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/lab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/lab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/lab/Alert/Alert' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Alert' {
  declare module.exports: any;
}

declare module '@material-ui/lab/AlertTitle/AlertTitle' {
  declare module.exports: any;
}

declare module '@material-ui/lab/AlertTitle' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Autocomplete/Autocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Autocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/AvatarGroup/AvatarGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/AvatarGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Alert/Alert' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Alert' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/AlertTitle/AlertTitle' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/AlertTitle' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Autocomplete/Autocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Autocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/AvatarGroup/AvatarGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/AvatarGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/Add' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/ArrowDropDown' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/Close' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/ErrorOutline' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/FirstPage' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/InfoOutlined' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/LastPage' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/NavigateBefore' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/NavigateNext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/ReportProblemOutlined' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/Star' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/internal/svg-icons/SuccessOutlined' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Pagination' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Pagination/Pagination' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Pagination/usePagination' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/PaginationItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/PaginationItem/PaginationItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Rating' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Rating/Rating' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Skeleton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Skeleton/Skeleton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDial' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDial/SpeedDial' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDialAction' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDialAction/SpeedDialAction' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDialIcon' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/SpeedDialIcon/SpeedDialIcon' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TabContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TabContext/TabContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TabList' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TabList/TabList' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TabPanel' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TabPanel/TabPanel' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Timeline' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Timeline/Timeline' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/Timeline/TimelineContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineConnector' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineConnector/TimelineConnector' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineContent/TimelineContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineDot' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineDot/TimelineDot' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineItem/TimelineItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineItem/TimelineItemContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineOppositeContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineOppositeContent/TimelineOppositeContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineSeparator' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TimelineSeparator/TimelineSeparator' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButton/ToggleButton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButtonGroup/isValueSelected' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/ToggleButtonGroup/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TreeItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TreeItem/TreeItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TreeView' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TreeView/TreeView' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/TreeView/TreeViewContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/useAutocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/es/useAutocomplete/useAutocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Alert/Alert' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Alert' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/AlertTitle/AlertTitle' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/AlertTitle' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Autocomplete/Autocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Autocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/AvatarGroup/AvatarGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/AvatarGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/Add' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/ArrowDropDown' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/Close' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/ErrorOutline' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/FirstPage' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/InfoOutlined' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/LastPage' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/NavigateBefore' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/NavigateNext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/ReportProblemOutlined' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/Star' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/internal/svg-icons/SuccessOutlined' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Pagination' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Pagination/Pagination' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Pagination/usePagination' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/PaginationItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/PaginationItem/PaginationItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Rating' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Rating/Rating' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Skeleton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Skeleton/Skeleton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/SpeedDial' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/SpeedDial/SpeedDial' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/SpeedDialAction' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/SpeedDialAction/SpeedDialAction' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/SpeedDialIcon' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/SpeedDialIcon/SpeedDialIcon' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TabContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TabContext/TabContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TabList' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TabList/TabList' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TabPanel' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TabPanel/TabPanel' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Timeline' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Timeline/Timeline' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/Timeline/TimelineContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineConnector' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineConnector/TimelineConnector' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineContent/TimelineContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineDot' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineDot/TimelineDot' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineItem/TimelineItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineItem/TimelineItemContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineOppositeContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineOppositeContent/TimelineOppositeContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineSeparator' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TimelineSeparator/TimelineSeparator' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/ToggleButton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/ToggleButton/ToggleButton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/ToggleButtonGroup/isValueSelected' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/ToggleButtonGroup/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TreeItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TreeItem/TreeItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TreeView' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TreeView/TreeView' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/TreeView/TreeViewContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/useAutocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/esm/useAutocomplete/useAutocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/Add' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/ArrowDropDown' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/Close' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/ErrorOutline' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/FirstPage' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/InfoOutlined' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/LastPage' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/NavigateBefore' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/NavigateNext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/ReportProblemOutlined' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/Star' {
  declare module.exports: any;
}

declare module '@material-ui/lab/internal/svg-icons/SuccessOutlined' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Pagination' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Pagination/Pagination' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Pagination/usePagination' {
  declare module.exports: any;
}

declare module '@material-ui/lab/PaginationItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/PaginationItem/PaginationItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Rating' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Rating/Rating' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Skeleton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Skeleton/Skeleton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDial' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDial/SpeedDial' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDialAction' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDialAction/SpeedDialAction' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDialIcon' {
  declare module.exports: any;
}

declare module '@material-ui/lab/SpeedDialIcon/SpeedDialIcon' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TabContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TabContext/TabContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TabList' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TabList/TabList' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TabPanel' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TabPanel/TabPanel' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Timeline' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Timeline/Timeline' {
  declare module.exports: any;
}

declare module '@material-ui/lab/Timeline/TimelineContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineConnector' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineConnector/TimelineConnector' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineContent/TimelineContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineDot' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineDot/TimelineDot' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineItem/TimelineItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineItem/TimelineItemContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineOppositeContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineOppositeContent/TimelineOppositeContent' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineSeparator' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TimelineSeparator/TimelineSeparator' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButton/ToggleButton' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButtonGroup/isValueSelected' {
  declare module.exports: any;
}

declare module '@material-ui/lab/ToggleButtonGroup/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TreeItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TreeItem/TreeItem' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TreeView' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TreeView/TreeView' {
  declare module.exports: any;
}

declare module '@material-ui/lab/TreeView/TreeViewContext' {
  declare module.exports: any;
}

declare module '@material-ui/lab/useAutocomplete' {
  declare module.exports: any;
}

declare module '@material-ui/lab/useAutocomplete/useAutocomplete' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/lab/Alert/Alert.js' {
  declare module.exports: $Exports<'@material-ui/lab/Alert/Alert'>;
}
declare module '@material-ui/lab/Alert/index' {
  declare module.exports: $Exports<'@material-ui/lab/Alert'>;
}
declare module '@material-ui/lab/Alert/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/Alert'>;
}
declare module '@material-ui/lab/AlertTitle/AlertTitle.js' {
  declare module.exports: $Exports<'@material-ui/lab/AlertTitle/AlertTitle'>;
}
declare module '@material-ui/lab/AlertTitle/index' {
  declare module.exports: $Exports<'@material-ui/lab/AlertTitle'>;
}
declare module '@material-ui/lab/AlertTitle/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/AlertTitle'>;
}
declare module '@material-ui/lab/Autocomplete/Autocomplete.js' {
  declare module.exports: $Exports<'@material-ui/lab/Autocomplete/Autocomplete'>;
}
declare module '@material-ui/lab/Autocomplete/index' {
  declare module.exports: $Exports<'@material-ui/lab/Autocomplete'>;
}
declare module '@material-ui/lab/Autocomplete/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/Autocomplete'>;
}
declare module '@material-ui/lab/AvatarGroup/AvatarGroup.js' {
  declare module.exports: $Exports<'@material-ui/lab/AvatarGroup/AvatarGroup'>;
}
declare module '@material-ui/lab/AvatarGroup/index' {
  declare module.exports: $Exports<'@material-ui/lab/AvatarGroup'>;
}
declare module '@material-ui/lab/AvatarGroup/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/AvatarGroup'>;
}
declare module '@material-ui/lab/es/Alert/Alert.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Alert/Alert'>;
}
declare module '@material-ui/lab/es/Alert/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/Alert'>;
}
declare module '@material-ui/lab/es/Alert/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Alert'>;
}
declare module '@material-ui/lab/es/AlertTitle/AlertTitle.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/AlertTitle/AlertTitle'>;
}
declare module '@material-ui/lab/es/AlertTitle/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/AlertTitle'>;
}
declare module '@material-ui/lab/es/AlertTitle/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/AlertTitle'>;
}
declare module '@material-ui/lab/es/Autocomplete/Autocomplete.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Autocomplete/Autocomplete'>;
}
declare module '@material-ui/lab/es/Autocomplete/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/Autocomplete'>;
}
declare module '@material-ui/lab/es/Autocomplete/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Autocomplete'>;
}
declare module '@material-ui/lab/es/AvatarGroup/AvatarGroup.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/AvatarGroup/AvatarGroup'>;
}
declare module '@material-ui/lab/es/AvatarGroup/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/AvatarGroup'>;
}
declare module '@material-ui/lab/es/AvatarGroup/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/AvatarGroup'>;
}
declare module '@material-ui/lab/es/index' {
  declare module.exports: $Exports<'@material-ui/lab/es'>;
}
declare module '@material-ui/lab/es/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/Add.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/Add'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/ArrowDropDown.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/ArrowDropDown'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/Close.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/Close'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/ErrorOutline.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/ErrorOutline'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/FirstPage.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/FirstPage'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/InfoOutlined.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/InfoOutlined'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/LastPage.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/LastPage'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/NavigateBefore.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/NavigateBefore'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/NavigateNext.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/NavigateNext'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/ReportProblemOutlined.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/ReportProblemOutlined'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/Star.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/Star'>;
}
declare module '@material-ui/lab/es/internal/svg-icons/SuccessOutlined.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/internal/svg-icons/SuccessOutlined'>;
}
declare module '@material-ui/lab/es/Pagination/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/Pagination'>;
}
declare module '@material-ui/lab/es/Pagination/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Pagination'>;
}
declare module '@material-ui/lab/es/Pagination/Pagination.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Pagination/Pagination'>;
}
declare module '@material-ui/lab/es/Pagination/usePagination.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Pagination/usePagination'>;
}
declare module '@material-ui/lab/es/PaginationItem/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/PaginationItem'>;
}
declare module '@material-ui/lab/es/PaginationItem/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/PaginationItem'>;
}
declare module '@material-ui/lab/es/PaginationItem/PaginationItem.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/PaginationItem/PaginationItem'>;
}
declare module '@material-ui/lab/es/Rating/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/Rating'>;
}
declare module '@material-ui/lab/es/Rating/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Rating'>;
}
declare module '@material-ui/lab/es/Rating/Rating.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Rating/Rating'>;
}
declare module '@material-ui/lab/es/Skeleton/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/Skeleton'>;
}
declare module '@material-ui/lab/es/Skeleton/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Skeleton'>;
}
declare module '@material-ui/lab/es/Skeleton/Skeleton.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Skeleton/Skeleton'>;
}
declare module '@material-ui/lab/es/SpeedDial/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDial'>;
}
declare module '@material-ui/lab/es/SpeedDial/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDial'>;
}
declare module '@material-ui/lab/es/SpeedDial/SpeedDial.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDial/SpeedDial'>;
}
declare module '@material-ui/lab/es/SpeedDialAction/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDialAction'>;
}
declare module '@material-ui/lab/es/SpeedDialAction/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDialAction'>;
}
declare module '@material-ui/lab/es/SpeedDialAction/SpeedDialAction.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDialAction/SpeedDialAction'>;
}
declare module '@material-ui/lab/es/SpeedDialIcon/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDialIcon'>;
}
declare module '@material-ui/lab/es/SpeedDialIcon/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDialIcon'>;
}
declare module '@material-ui/lab/es/SpeedDialIcon/SpeedDialIcon.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/SpeedDialIcon/SpeedDialIcon'>;
}
declare module '@material-ui/lab/es/TabContext/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TabContext'>;
}
declare module '@material-ui/lab/es/TabContext/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TabContext'>;
}
declare module '@material-ui/lab/es/TabContext/TabContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TabContext/TabContext'>;
}
declare module '@material-ui/lab/es/TabList/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TabList'>;
}
declare module '@material-ui/lab/es/TabList/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TabList'>;
}
declare module '@material-ui/lab/es/TabList/TabList.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TabList/TabList'>;
}
declare module '@material-ui/lab/es/TabPanel/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TabPanel'>;
}
declare module '@material-ui/lab/es/TabPanel/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TabPanel'>;
}
declare module '@material-ui/lab/es/TabPanel/TabPanel.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TabPanel/TabPanel'>;
}
declare module '@material-ui/lab/es/Timeline/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/Timeline'>;
}
declare module '@material-ui/lab/es/Timeline/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Timeline'>;
}
declare module '@material-ui/lab/es/Timeline/Timeline.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Timeline/Timeline'>;
}
declare module '@material-ui/lab/es/Timeline/TimelineContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/Timeline/TimelineContext'>;
}
declare module '@material-ui/lab/es/TimelineConnector/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineConnector'>;
}
declare module '@material-ui/lab/es/TimelineConnector/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineConnector'>;
}
declare module '@material-ui/lab/es/TimelineConnector/TimelineConnector.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineConnector/TimelineConnector'>;
}
declare module '@material-ui/lab/es/TimelineContent/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineContent'>;
}
declare module '@material-ui/lab/es/TimelineContent/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineContent'>;
}
declare module '@material-ui/lab/es/TimelineContent/TimelineContent.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineContent/TimelineContent'>;
}
declare module '@material-ui/lab/es/TimelineDot/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineDot'>;
}
declare module '@material-ui/lab/es/TimelineDot/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineDot'>;
}
declare module '@material-ui/lab/es/TimelineDot/TimelineDot.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineDot/TimelineDot'>;
}
declare module '@material-ui/lab/es/TimelineItem/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineItem'>;
}
declare module '@material-ui/lab/es/TimelineItem/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineItem'>;
}
declare module '@material-ui/lab/es/TimelineItem/TimelineItem.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineItem/TimelineItem'>;
}
declare module '@material-ui/lab/es/TimelineItem/TimelineItemContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineItem/TimelineItemContext'>;
}
declare module '@material-ui/lab/es/TimelineOppositeContent/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineOppositeContent'>;
}
declare module '@material-ui/lab/es/TimelineOppositeContent/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineOppositeContent'>;
}
declare module '@material-ui/lab/es/TimelineOppositeContent/TimelineOppositeContent.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineOppositeContent/TimelineOppositeContent'>;
}
declare module '@material-ui/lab/es/TimelineSeparator/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineSeparator'>;
}
declare module '@material-ui/lab/es/TimelineSeparator/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineSeparator'>;
}
declare module '@material-ui/lab/es/TimelineSeparator/TimelineSeparator.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TimelineSeparator/TimelineSeparator'>;
}
declare module '@material-ui/lab/es/ToggleButton/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButton'>;
}
declare module '@material-ui/lab/es/ToggleButton/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButton'>;
}
declare module '@material-ui/lab/es/ToggleButton/ToggleButton.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButton/ToggleButton'>;
}
declare module '@material-ui/lab/es/ToggleButtonGroup/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/es/ToggleButtonGroup/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/es/ToggleButtonGroup/isValueSelected.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButtonGroup/isValueSelected'>;
}
declare module '@material-ui/lab/es/ToggleButtonGroup/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/ToggleButtonGroup/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/es/TreeItem/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TreeItem'>;
}
declare module '@material-ui/lab/es/TreeItem/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TreeItem'>;
}
declare module '@material-ui/lab/es/TreeItem/TreeItem.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TreeItem/TreeItem'>;
}
declare module '@material-ui/lab/es/TreeView/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/TreeView'>;
}
declare module '@material-ui/lab/es/TreeView/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TreeView'>;
}
declare module '@material-ui/lab/es/TreeView/TreeView.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TreeView/TreeView'>;
}
declare module '@material-ui/lab/es/TreeView/TreeViewContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/TreeView/TreeViewContext'>;
}
declare module '@material-ui/lab/es/useAutocomplete/index' {
  declare module.exports: $Exports<'@material-ui/lab/es/useAutocomplete'>;
}
declare module '@material-ui/lab/es/useAutocomplete/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/useAutocomplete'>;
}
declare module '@material-ui/lab/es/useAutocomplete/useAutocomplete.js' {
  declare module.exports: $Exports<'@material-ui/lab/es/useAutocomplete/useAutocomplete'>;
}
declare module '@material-ui/lab/esm/Alert/Alert.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Alert/Alert'>;
}
declare module '@material-ui/lab/esm/Alert/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Alert'>;
}
declare module '@material-ui/lab/esm/Alert/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Alert'>;
}
declare module '@material-ui/lab/esm/AlertTitle/AlertTitle.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/AlertTitle/AlertTitle'>;
}
declare module '@material-ui/lab/esm/AlertTitle/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/AlertTitle'>;
}
declare module '@material-ui/lab/esm/AlertTitle/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/AlertTitle'>;
}
declare module '@material-ui/lab/esm/Autocomplete/Autocomplete.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Autocomplete/Autocomplete'>;
}
declare module '@material-ui/lab/esm/Autocomplete/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Autocomplete'>;
}
declare module '@material-ui/lab/esm/Autocomplete/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Autocomplete'>;
}
declare module '@material-ui/lab/esm/AvatarGroup/AvatarGroup.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/AvatarGroup/AvatarGroup'>;
}
declare module '@material-ui/lab/esm/AvatarGroup/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/AvatarGroup'>;
}
declare module '@material-ui/lab/esm/AvatarGroup/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/AvatarGroup'>;
}
declare module '@material-ui/lab/esm/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm'>;
}
declare module '@material-ui/lab/esm/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/Add.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/Add'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/ArrowDropDown.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/ArrowDropDown'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/Close.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/Close'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/ErrorOutline.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/ErrorOutline'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/FirstPage.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/FirstPage'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/InfoOutlined.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/InfoOutlined'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/LastPage.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/LastPage'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/NavigateBefore.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/NavigateBefore'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/NavigateNext.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/NavigateNext'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/ReportProblemOutlined.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/ReportProblemOutlined'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/Star.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/Star'>;
}
declare module '@material-ui/lab/esm/internal/svg-icons/SuccessOutlined.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/internal/svg-icons/SuccessOutlined'>;
}
declare module '@material-ui/lab/esm/Pagination/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Pagination'>;
}
declare module '@material-ui/lab/esm/Pagination/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Pagination'>;
}
declare module '@material-ui/lab/esm/Pagination/Pagination.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Pagination/Pagination'>;
}
declare module '@material-ui/lab/esm/Pagination/usePagination.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Pagination/usePagination'>;
}
declare module '@material-ui/lab/esm/PaginationItem/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/PaginationItem'>;
}
declare module '@material-ui/lab/esm/PaginationItem/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/PaginationItem'>;
}
declare module '@material-ui/lab/esm/PaginationItem/PaginationItem.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/PaginationItem/PaginationItem'>;
}
declare module '@material-ui/lab/esm/Rating/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Rating'>;
}
declare module '@material-ui/lab/esm/Rating/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Rating'>;
}
declare module '@material-ui/lab/esm/Rating/Rating.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Rating/Rating'>;
}
declare module '@material-ui/lab/esm/Skeleton/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Skeleton'>;
}
declare module '@material-ui/lab/esm/Skeleton/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Skeleton'>;
}
declare module '@material-ui/lab/esm/Skeleton/Skeleton.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Skeleton/Skeleton'>;
}
declare module '@material-ui/lab/esm/SpeedDial/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/SpeedDial'>;
}
declare module '@material-ui/lab/esm/SpeedDial/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/SpeedDial'>;
}
declare module '@material-ui/lab/esm/SpeedDial/SpeedDial.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/SpeedDial/SpeedDial'>;
}
declare module '@material-ui/lab/esm/SpeedDialAction/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/SpeedDialAction'>;
}
declare module '@material-ui/lab/esm/SpeedDialAction/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/SpeedDialAction'>;
}
declare module '@material-ui/lab/esm/SpeedDialAction/SpeedDialAction.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/SpeedDialAction/SpeedDialAction'>;
}
declare module '@material-ui/lab/esm/SpeedDialIcon/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/SpeedDialIcon'>;
}
declare module '@material-ui/lab/esm/SpeedDialIcon/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/SpeedDialIcon'>;
}
declare module '@material-ui/lab/esm/SpeedDialIcon/SpeedDialIcon.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/SpeedDialIcon/SpeedDialIcon'>;
}
declare module '@material-ui/lab/esm/TabContext/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TabContext'>;
}
declare module '@material-ui/lab/esm/TabContext/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TabContext'>;
}
declare module '@material-ui/lab/esm/TabContext/TabContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TabContext/TabContext'>;
}
declare module '@material-ui/lab/esm/TabList/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TabList'>;
}
declare module '@material-ui/lab/esm/TabList/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TabList'>;
}
declare module '@material-ui/lab/esm/TabList/TabList.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TabList/TabList'>;
}
declare module '@material-ui/lab/esm/TabPanel/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TabPanel'>;
}
declare module '@material-ui/lab/esm/TabPanel/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TabPanel'>;
}
declare module '@material-ui/lab/esm/TabPanel/TabPanel.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TabPanel/TabPanel'>;
}
declare module '@material-ui/lab/esm/Timeline/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Timeline'>;
}
declare module '@material-ui/lab/esm/Timeline/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Timeline'>;
}
declare module '@material-ui/lab/esm/Timeline/Timeline.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Timeline/Timeline'>;
}
declare module '@material-ui/lab/esm/Timeline/TimelineContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/Timeline/TimelineContext'>;
}
declare module '@material-ui/lab/esm/TimelineConnector/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineConnector'>;
}
declare module '@material-ui/lab/esm/TimelineConnector/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineConnector'>;
}
declare module '@material-ui/lab/esm/TimelineConnector/TimelineConnector.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineConnector/TimelineConnector'>;
}
declare module '@material-ui/lab/esm/TimelineContent/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineContent'>;
}
declare module '@material-ui/lab/esm/TimelineContent/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineContent'>;
}
declare module '@material-ui/lab/esm/TimelineContent/TimelineContent.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineContent/TimelineContent'>;
}
declare module '@material-ui/lab/esm/TimelineDot/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineDot'>;
}
declare module '@material-ui/lab/esm/TimelineDot/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineDot'>;
}
declare module '@material-ui/lab/esm/TimelineDot/TimelineDot.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineDot/TimelineDot'>;
}
declare module '@material-ui/lab/esm/TimelineItem/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineItem'>;
}
declare module '@material-ui/lab/esm/TimelineItem/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineItem'>;
}
declare module '@material-ui/lab/esm/TimelineItem/TimelineItem.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineItem/TimelineItem'>;
}
declare module '@material-ui/lab/esm/TimelineItem/TimelineItemContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineItem/TimelineItemContext'>;
}
declare module '@material-ui/lab/esm/TimelineOppositeContent/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineOppositeContent'>;
}
declare module '@material-ui/lab/esm/TimelineOppositeContent/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineOppositeContent'>;
}
declare module '@material-ui/lab/esm/TimelineOppositeContent/TimelineOppositeContent.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineOppositeContent/TimelineOppositeContent'>;
}
declare module '@material-ui/lab/esm/TimelineSeparator/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineSeparator'>;
}
declare module '@material-ui/lab/esm/TimelineSeparator/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineSeparator'>;
}
declare module '@material-ui/lab/esm/TimelineSeparator/TimelineSeparator.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TimelineSeparator/TimelineSeparator'>;
}
declare module '@material-ui/lab/esm/ToggleButton/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/ToggleButton'>;
}
declare module '@material-ui/lab/esm/ToggleButton/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/ToggleButton'>;
}
declare module '@material-ui/lab/esm/ToggleButton/ToggleButton.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/ToggleButton/ToggleButton'>;
}
declare module '@material-ui/lab/esm/ToggleButtonGroup/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/esm/ToggleButtonGroup/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/esm/ToggleButtonGroup/isValueSelected.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/ToggleButtonGroup/isValueSelected'>;
}
declare module '@material-ui/lab/esm/ToggleButtonGroup/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/ToggleButtonGroup/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/esm/TreeItem/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TreeItem'>;
}
declare module '@material-ui/lab/esm/TreeItem/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TreeItem'>;
}
declare module '@material-ui/lab/esm/TreeItem/TreeItem.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TreeItem/TreeItem'>;
}
declare module '@material-ui/lab/esm/TreeView/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TreeView'>;
}
declare module '@material-ui/lab/esm/TreeView/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TreeView'>;
}
declare module '@material-ui/lab/esm/TreeView/TreeView.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TreeView/TreeView'>;
}
declare module '@material-ui/lab/esm/TreeView/TreeViewContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/TreeView/TreeViewContext'>;
}
declare module '@material-ui/lab/esm/useAutocomplete/index' {
  declare module.exports: $Exports<'@material-ui/lab/esm/useAutocomplete'>;
}
declare module '@material-ui/lab/esm/useAutocomplete/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/useAutocomplete'>;
}
declare module '@material-ui/lab/esm/useAutocomplete/useAutocomplete.js' {
  declare module.exports: $Exports<'@material-ui/lab/esm/useAutocomplete/useAutocomplete'>;
}
declare module '@material-ui/lab/index' {
  declare module.exports: $Exports<'@material-ui/lab'>;
}
declare module '@material-ui/lab/index.js' {
  declare module.exports: $Exports<'@material-ui/lab'>;
}
declare module '@material-ui/lab/internal/svg-icons/Add.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/Add'>;
}
declare module '@material-ui/lab/internal/svg-icons/ArrowDropDown.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/ArrowDropDown'>;
}
declare module '@material-ui/lab/internal/svg-icons/Close.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/Close'>;
}
declare module '@material-ui/lab/internal/svg-icons/ErrorOutline.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/ErrorOutline'>;
}
declare module '@material-ui/lab/internal/svg-icons/FirstPage.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/FirstPage'>;
}
declare module '@material-ui/lab/internal/svg-icons/InfoOutlined.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/InfoOutlined'>;
}
declare module '@material-ui/lab/internal/svg-icons/LastPage.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/LastPage'>;
}
declare module '@material-ui/lab/internal/svg-icons/NavigateBefore.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/NavigateBefore'>;
}
declare module '@material-ui/lab/internal/svg-icons/NavigateNext.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/NavigateNext'>;
}
declare module '@material-ui/lab/internal/svg-icons/ReportProblemOutlined.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/ReportProblemOutlined'>;
}
declare module '@material-ui/lab/internal/svg-icons/Star.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/Star'>;
}
declare module '@material-ui/lab/internal/svg-icons/SuccessOutlined.js' {
  declare module.exports: $Exports<'@material-ui/lab/internal/svg-icons/SuccessOutlined'>;
}
declare module '@material-ui/lab/Pagination/index' {
  declare module.exports: $Exports<'@material-ui/lab/Pagination'>;
}
declare module '@material-ui/lab/Pagination/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/Pagination'>;
}
declare module '@material-ui/lab/Pagination/Pagination.js' {
  declare module.exports: $Exports<'@material-ui/lab/Pagination/Pagination'>;
}
declare module '@material-ui/lab/Pagination/usePagination.js' {
  declare module.exports: $Exports<'@material-ui/lab/Pagination/usePagination'>;
}
declare module '@material-ui/lab/PaginationItem/index' {
  declare module.exports: $Exports<'@material-ui/lab/PaginationItem'>;
}
declare module '@material-ui/lab/PaginationItem/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/PaginationItem'>;
}
declare module '@material-ui/lab/PaginationItem/PaginationItem.js' {
  declare module.exports: $Exports<'@material-ui/lab/PaginationItem/PaginationItem'>;
}
declare module '@material-ui/lab/Rating/index' {
  declare module.exports: $Exports<'@material-ui/lab/Rating'>;
}
declare module '@material-ui/lab/Rating/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/Rating'>;
}
declare module '@material-ui/lab/Rating/Rating.js' {
  declare module.exports: $Exports<'@material-ui/lab/Rating/Rating'>;
}
declare module '@material-ui/lab/Skeleton/index' {
  declare module.exports: $Exports<'@material-ui/lab/Skeleton'>;
}
declare module '@material-ui/lab/Skeleton/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/Skeleton'>;
}
declare module '@material-ui/lab/Skeleton/Skeleton.js' {
  declare module.exports: $Exports<'@material-ui/lab/Skeleton/Skeleton'>;
}
declare module '@material-ui/lab/SpeedDial/index' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDial'>;
}
declare module '@material-ui/lab/SpeedDial/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDial'>;
}
declare module '@material-ui/lab/SpeedDial/SpeedDial.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDial/SpeedDial'>;
}
declare module '@material-ui/lab/SpeedDialAction/index' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialAction'>;
}
declare module '@material-ui/lab/SpeedDialAction/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialAction'>;
}
declare module '@material-ui/lab/SpeedDialAction/SpeedDialAction.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialAction/SpeedDialAction'>;
}
declare module '@material-ui/lab/SpeedDialIcon/index' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialIcon'>;
}
declare module '@material-ui/lab/SpeedDialIcon/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialIcon'>;
}
declare module '@material-ui/lab/SpeedDialIcon/SpeedDialIcon.js' {
  declare module.exports: $Exports<'@material-ui/lab/SpeedDialIcon/SpeedDialIcon'>;
}
declare module '@material-ui/lab/TabContext/index' {
  declare module.exports: $Exports<'@material-ui/lab/TabContext'>;
}
declare module '@material-ui/lab/TabContext/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TabContext'>;
}
declare module '@material-ui/lab/TabContext/TabContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/TabContext/TabContext'>;
}
declare module '@material-ui/lab/TabList/index' {
  declare module.exports: $Exports<'@material-ui/lab/TabList'>;
}
declare module '@material-ui/lab/TabList/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TabList'>;
}
declare module '@material-ui/lab/TabList/TabList.js' {
  declare module.exports: $Exports<'@material-ui/lab/TabList/TabList'>;
}
declare module '@material-ui/lab/TabPanel/index' {
  declare module.exports: $Exports<'@material-ui/lab/TabPanel'>;
}
declare module '@material-ui/lab/TabPanel/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TabPanel'>;
}
declare module '@material-ui/lab/TabPanel/TabPanel.js' {
  declare module.exports: $Exports<'@material-ui/lab/TabPanel/TabPanel'>;
}
declare module '@material-ui/lab/Timeline/index' {
  declare module.exports: $Exports<'@material-ui/lab/Timeline'>;
}
declare module '@material-ui/lab/Timeline/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/Timeline'>;
}
declare module '@material-ui/lab/Timeline/Timeline.js' {
  declare module.exports: $Exports<'@material-ui/lab/Timeline/Timeline'>;
}
declare module '@material-ui/lab/Timeline/TimelineContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/Timeline/TimelineContext'>;
}
declare module '@material-ui/lab/TimelineConnector/index' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineConnector'>;
}
declare module '@material-ui/lab/TimelineConnector/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineConnector'>;
}
declare module '@material-ui/lab/TimelineConnector/TimelineConnector.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineConnector/TimelineConnector'>;
}
declare module '@material-ui/lab/TimelineContent/index' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineContent'>;
}
declare module '@material-ui/lab/TimelineContent/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineContent'>;
}
declare module '@material-ui/lab/TimelineContent/TimelineContent.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineContent/TimelineContent'>;
}
declare module '@material-ui/lab/TimelineDot/index' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineDot'>;
}
declare module '@material-ui/lab/TimelineDot/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineDot'>;
}
declare module '@material-ui/lab/TimelineDot/TimelineDot.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineDot/TimelineDot'>;
}
declare module '@material-ui/lab/TimelineItem/index' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineItem'>;
}
declare module '@material-ui/lab/TimelineItem/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineItem'>;
}
declare module '@material-ui/lab/TimelineItem/TimelineItem.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineItem/TimelineItem'>;
}
declare module '@material-ui/lab/TimelineItem/TimelineItemContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineItem/TimelineItemContext'>;
}
declare module '@material-ui/lab/TimelineOppositeContent/index' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineOppositeContent'>;
}
declare module '@material-ui/lab/TimelineOppositeContent/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineOppositeContent'>;
}
declare module '@material-ui/lab/TimelineOppositeContent/TimelineOppositeContent.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineOppositeContent/TimelineOppositeContent'>;
}
declare module '@material-ui/lab/TimelineSeparator/index' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineSeparator'>;
}
declare module '@material-ui/lab/TimelineSeparator/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineSeparator'>;
}
declare module '@material-ui/lab/TimelineSeparator/TimelineSeparator.js' {
  declare module.exports: $Exports<'@material-ui/lab/TimelineSeparator/TimelineSeparator'>;
}
declare module '@material-ui/lab/ToggleButton/index' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButton'>;
}
declare module '@material-ui/lab/ToggleButton/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButton'>;
}
declare module '@material-ui/lab/ToggleButton/ToggleButton.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButton/ToggleButton'>;
}
declare module '@material-ui/lab/ToggleButtonGroup/index' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/ToggleButtonGroup/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/ToggleButtonGroup/isValueSelected.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButtonGroup/isValueSelected'>;
}
declare module '@material-ui/lab/ToggleButtonGroup/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'@material-ui/lab/ToggleButtonGroup/ToggleButtonGroup'>;
}
declare module '@material-ui/lab/TreeItem/index' {
  declare module.exports: $Exports<'@material-ui/lab/TreeItem'>;
}
declare module '@material-ui/lab/TreeItem/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TreeItem'>;
}
declare module '@material-ui/lab/TreeItem/TreeItem.js' {
  declare module.exports: $Exports<'@material-ui/lab/TreeItem/TreeItem'>;
}
declare module '@material-ui/lab/TreeView/index' {
  declare module.exports: $Exports<'@material-ui/lab/TreeView'>;
}
declare module '@material-ui/lab/TreeView/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/TreeView'>;
}
declare module '@material-ui/lab/TreeView/TreeView.js' {
  declare module.exports: $Exports<'@material-ui/lab/TreeView/TreeView'>;
}
declare module '@material-ui/lab/TreeView/TreeViewContext.js' {
  declare module.exports: $Exports<'@material-ui/lab/TreeView/TreeViewContext'>;
}
declare module '@material-ui/lab/useAutocomplete/index' {
  declare module.exports: $Exports<'@material-ui/lab/useAutocomplete'>;
}
declare module '@material-ui/lab/useAutocomplete/index.js' {
  declare module.exports: $Exports<'@material-ui/lab/useAutocomplete'>;
}
declare module '@material-ui/lab/useAutocomplete/useAutocomplete.js' {
  declare module.exports: $Exports<'@material-ui/lab/useAutocomplete/useAutocomplete'>;
}
