// flow-typed signature: e6c4a8210a743634f481b03e7f551584
// flow-typed version: <<STUB>>/@material-ui/pickers_v3.2.10/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/pickers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/pickers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/pickers/_helpers/date-utils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_helpers/text-field-helper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_helpers/time-utils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_helpers/utils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useIsLandscape' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useKeyboardPickerState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useKeyDown' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useOpenState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/usePickerState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useStaticState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useUtils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useViews' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/icons/ArrowLeftIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/icons/ArrowRightIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/icons/DateRangeIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/icons/KeyboardIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/icons/TimeIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/KeyboardDateInput' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/ModalDialog' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/PickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/PureDateInput' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/ToolbarButton' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/ToolbarText' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/WithUtils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/constants/ClockType' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/constants/dimensions' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/constants/prop-types' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DatePicker/DatePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DatePicker/DatePickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DatePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DateTimePicker/DateTimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DateTimePicker/DateTimePickerTabs' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DateTimePicker/DateTimePickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DateTimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers.esm' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers.umd' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers.umd.min' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Calendar-11ae61f6' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Calendar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Clock-48fde975' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Clock' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/ClockView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/DatePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/DateTimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Day' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/makePickerWithState-5a79cb8a' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Picker-ccd9ba90' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Picker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/TimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/TimePickerToolbar-81100fab' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/useUtils-cfb96ac9' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Wrapper-241966d7' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/MuiPickersUtilsProvider' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Picker/makePickerWithState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Picker/Picker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/TimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/TimePicker/TimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/TimePicker/TimePickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/typings/BasePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/typings/date' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/typings/extendMui' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/typings/overrides' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Calendar/Calendar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Calendar/CalendarHeader' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Calendar/Day' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Calendar/DayWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Calendar/SlideTransition' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Clock/Clock' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Clock/ClockNumber' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Clock/ClockNumbers' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Clock/ClockPointer' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Clock/ClockView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Month/Month' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Month/MonthView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Year/Year' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Year/YearView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/wrappers/InlineWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/wrappers/ModalWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/wrappers/StaticWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/wrappers/Wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/pickers/_helpers/date-utils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_helpers/date-utils'>;
}
declare module '@material-ui/pickers/_helpers/text-field-helper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_helpers/text-field-helper'>;
}
declare module '@material-ui/pickers/_helpers/time-utils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_helpers/time-utils'>;
}
declare module '@material-ui/pickers/_helpers/utils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_helpers/utils'>;
}
declare module '@material-ui/pickers/_shared/hooks/useIsLandscape.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useIsLandscape'>;
}
declare module '@material-ui/pickers/_shared/hooks/useKeyboardPickerState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useKeyboardPickerState'>;
}
declare module '@material-ui/pickers/_shared/hooks/useKeyDown.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useKeyDown'>;
}
declare module '@material-ui/pickers/_shared/hooks/useOpenState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useOpenState'>;
}
declare module '@material-ui/pickers/_shared/hooks/usePickerState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/usePickerState'>;
}
declare module '@material-ui/pickers/_shared/hooks/useStaticState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useStaticState'>;
}
declare module '@material-ui/pickers/_shared/hooks/useUtils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useUtils'>;
}
declare module '@material-ui/pickers/_shared/hooks/useViews.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useViews'>;
}
declare module '@material-ui/pickers/_shared/icons/ArrowLeftIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/icons/ArrowLeftIcon'>;
}
declare module '@material-ui/pickers/_shared/icons/ArrowRightIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/icons/ArrowRightIcon'>;
}
declare module '@material-ui/pickers/_shared/icons/DateRangeIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/icons/DateRangeIcon'>;
}
declare module '@material-ui/pickers/_shared/icons/KeyboardIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/icons/KeyboardIcon'>;
}
declare module '@material-ui/pickers/_shared/icons/TimeIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/icons/TimeIcon'>;
}
declare module '@material-ui/pickers/_shared/KeyboardDateInput.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/KeyboardDateInput'>;
}
declare module '@material-ui/pickers/_shared/ModalDialog.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/ModalDialog'>;
}
declare module '@material-ui/pickers/_shared/PickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/PickerToolbar'>;
}
declare module '@material-ui/pickers/_shared/PureDateInput.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/PureDateInput'>;
}
declare module '@material-ui/pickers/_shared/ToolbarButton.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/ToolbarButton'>;
}
declare module '@material-ui/pickers/_shared/ToolbarText.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/ToolbarText'>;
}
declare module '@material-ui/pickers/_shared/WithUtils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/WithUtils'>;
}
declare module '@material-ui/pickers/constants/ClockType.js' {
  declare module.exports: $Exports<'@material-ui/pickers/constants/ClockType'>;
}
declare module '@material-ui/pickers/constants/dimensions.js' {
  declare module.exports: $Exports<'@material-ui/pickers/constants/dimensions'>;
}
declare module '@material-ui/pickers/constants/prop-types.js' {
  declare module.exports: $Exports<'@material-ui/pickers/constants/prop-types'>;
}
declare module '@material-ui/pickers/DatePicker/DatePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DatePicker/DatePicker'>;
}
declare module '@material-ui/pickers/DatePicker/DatePickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DatePicker/DatePickerToolbar'>;
}
declare module '@material-ui/pickers/DatePicker/index' {
  declare module.exports: $Exports<'@material-ui/pickers/DatePicker'>;
}
declare module '@material-ui/pickers/DatePicker/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DatePicker'>;
}
declare module '@material-ui/pickers/DateTimePicker/DateTimePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker/DateTimePicker'>;
}
declare module '@material-ui/pickers/DateTimePicker/DateTimePickerTabs.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker/DateTimePickerTabs'>;
}
declare module '@material-ui/pickers/DateTimePicker/DateTimePickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker/DateTimePickerToolbar'>;
}
declare module '@material-ui/pickers/DateTimePicker/index' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker'>;
}
declare module '@material-ui/pickers/DateTimePicker/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.esm.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers.esm'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.umd.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers.umd'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.umd.min.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers.umd.min'>;
}
declare module '@material-ui/pickers/esm/Calendar-11ae61f6.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Calendar-11ae61f6'>;
}
declare module '@material-ui/pickers/esm/Calendar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Calendar'>;
}
declare module '@material-ui/pickers/esm/Clock-48fde975.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Clock-48fde975'>;
}
declare module '@material-ui/pickers/esm/Clock.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Clock'>;
}
declare module '@material-ui/pickers/esm/ClockView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/ClockView'>;
}
declare module '@material-ui/pickers/esm/DatePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DatePicker'>;
}
declare module '@material-ui/pickers/esm/DateTimePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DateTimePicker'>;
}
declare module '@material-ui/pickers/esm/Day.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Day'>;
}
declare module '@material-ui/pickers/esm/index' {
  declare module.exports: $Exports<'@material-ui/pickers/esm'>;
}
declare module '@material-ui/pickers/esm/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm'>;
}
declare module '@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/makePickerWithState-5a79cb8a'>;
}
declare module '@material-ui/pickers/esm/Picker-ccd9ba90.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Picker-ccd9ba90'>;
}
declare module '@material-ui/pickers/esm/Picker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Picker'>;
}
declare module '@material-ui/pickers/esm/TimePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/TimePicker'>;
}
declare module '@material-ui/pickers/esm/TimePickerToolbar-81100fab.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/TimePickerToolbar-81100fab'>;
}
declare module '@material-ui/pickers/esm/useUtils-cfb96ac9.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/useUtils-cfb96ac9'>;
}
declare module '@material-ui/pickers/esm/Wrapper-241966d7.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Wrapper-241966d7'>;
}
declare module '@material-ui/pickers/index' {
  declare module.exports: $Exports<'@material-ui/pickers'>;
}
declare module '@material-ui/pickers/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers'>;
}
declare module '@material-ui/pickers/MuiPickersUtilsProvider.js' {
  declare module.exports: $Exports<'@material-ui/pickers/MuiPickersUtilsProvider'>;
}
declare module '@material-ui/pickers/Picker/makePickerWithState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Picker/makePickerWithState'>;
}
declare module '@material-ui/pickers/Picker/Picker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Picker/Picker'>;
}
declare module '@material-ui/pickers/TimePicker/index' {
  declare module.exports: $Exports<'@material-ui/pickers/TimePicker'>;
}
declare module '@material-ui/pickers/TimePicker/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/TimePicker'>;
}
declare module '@material-ui/pickers/TimePicker/TimePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/TimePicker/TimePicker'>;
}
declare module '@material-ui/pickers/TimePicker/TimePickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/TimePicker/TimePickerToolbar'>;
}
declare module '@material-ui/pickers/typings/BasePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/typings/BasePicker'>;
}
declare module '@material-ui/pickers/typings/date.js' {
  declare module.exports: $Exports<'@material-ui/pickers/typings/date'>;
}
declare module '@material-ui/pickers/typings/extendMui.js' {
  declare module.exports: $Exports<'@material-ui/pickers/typings/extendMui'>;
}
declare module '@material-ui/pickers/typings/overrides.js' {
  declare module.exports: $Exports<'@material-ui/pickers/typings/overrides'>;
}
declare module '@material-ui/pickers/views/Calendar/Calendar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Calendar/Calendar'>;
}
declare module '@material-ui/pickers/views/Calendar/CalendarHeader.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Calendar/CalendarHeader'>;
}
declare module '@material-ui/pickers/views/Calendar/Day.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Calendar/Day'>;
}
declare module '@material-ui/pickers/views/Calendar/DayWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Calendar/DayWrapper'>;
}
declare module '@material-ui/pickers/views/Calendar/SlideTransition.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Calendar/SlideTransition'>;
}
declare module '@material-ui/pickers/views/Clock/Clock.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Clock/Clock'>;
}
declare module '@material-ui/pickers/views/Clock/ClockNumber.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Clock/ClockNumber'>;
}
declare module '@material-ui/pickers/views/Clock/ClockNumbers.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Clock/ClockNumbers'>;
}
declare module '@material-ui/pickers/views/Clock/ClockPointer.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Clock/ClockPointer'>;
}
declare module '@material-ui/pickers/views/Clock/ClockView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Clock/ClockView'>;
}
declare module '@material-ui/pickers/views/Month/Month.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Month/Month'>;
}
declare module '@material-ui/pickers/views/Month/MonthView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Month/MonthView'>;
}
declare module '@material-ui/pickers/views/Year/Year.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Year/Year'>;
}
declare module '@material-ui/pickers/views/Year/YearView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Year/YearView'>;
}
declare module '@material-ui/pickers/wrappers/InlineWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/wrappers/InlineWrapper'>;
}
declare module '@material-ui/pickers/wrappers/ModalWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/wrappers/ModalWrapper'>;
}
declare module '@material-ui/pickers/wrappers/StaticWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/wrappers/StaticWrapper'>;
}
declare module '@material-ui/pickers/wrappers/Wrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/wrappers/Wrapper'>;
}
