// flow-typed signature: fde54174cb299b8d85d07373ef8352f9
// flow-typed version: <<STUB>>/@material-ui/pickers_v^4.0.0-alpha.12/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/pickers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/pickers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/pickers/adapter/date-fns/index.cjs' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/adapter/date-fns' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/adapter/dayjs/index.cjs' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/adapter/dayjs' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/adapter/luxon/index.cjs' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/adapter/luxon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/adapter/moment/index.cjs' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/adapter/moment' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Calendar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/CalendarSkeleton' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Clock-c2c3c22b' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Clock' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/ClockView-68b1ba14' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/ClockView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DatePicker-eb1dd2e7' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DatePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DateTimePicker-844e45bc' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DateTimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Day' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dimensions-f39eca69' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers.esm' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers.umd' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers.umd.min' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/LocalizationProvider' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/makePickerWithState-d83c633b' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Picker-858b30b6' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Picker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/TimePicker-af76ca08' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/TimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/useCanAutoFocus-1eacc580' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/useKeyDown-5aaf69f9' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/pickers/adapter/date-fns/index.cjs.js' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/date-fns/index.cjs'>;
}
declare module '@material-ui/pickers/adapter/date-fns/index' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/date-fns'>;
}
declare module '@material-ui/pickers/adapter/date-fns/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/date-fns'>;
}
declare module '@material-ui/pickers/adapter/dayjs/index.cjs.js' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/dayjs/index.cjs'>;
}
declare module '@material-ui/pickers/adapter/dayjs/index' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/dayjs'>;
}
declare module '@material-ui/pickers/adapter/dayjs/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/dayjs'>;
}
declare module '@material-ui/pickers/adapter/luxon/index.cjs.js' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/luxon/index.cjs'>;
}
declare module '@material-ui/pickers/adapter/luxon/index' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/luxon'>;
}
declare module '@material-ui/pickers/adapter/luxon/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/luxon'>;
}
declare module '@material-ui/pickers/adapter/moment/index.cjs.js' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/moment/index.cjs'>;
}
declare module '@material-ui/pickers/adapter/moment/index' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/moment'>;
}
declare module '@material-ui/pickers/adapter/moment/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/adapter/moment'>;
}
declare module '@material-ui/pickers/Calendar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Calendar'>;
}
declare module '@material-ui/pickers/CalendarSkeleton.js' {
  declare module.exports: $Exports<'@material-ui/pickers/CalendarSkeleton'>;
}
declare module '@material-ui/pickers/Clock-c2c3c22b.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Clock-c2c3c22b'>;
}
declare module '@material-ui/pickers/Clock.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Clock'>;
}
declare module '@material-ui/pickers/ClockView-68b1ba14.js' {
  declare module.exports: $Exports<'@material-ui/pickers/ClockView-68b1ba14'>;
}
declare module '@material-ui/pickers/ClockView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/ClockView'>;
}
declare module '@material-ui/pickers/DatePicker-eb1dd2e7.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DatePicker-eb1dd2e7'>;
}
declare module '@material-ui/pickers/DatePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DatePicker'>;
}
declare module '@material-ui/pickers/DateTimePicker-844e45bc.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker-844e45bc'>;
}
declare module '@material-ui/pickers/DateTimePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker'>;
}
declare module '@material-ui/pickers/Day.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Day'>;
}
declare module '@material-ui/pickers/dimensions-f39eca69.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dimensions-f39eca69'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.esm.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers.esm'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.umd.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers.umd'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.umd.min.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers.umd.min'>;
}
declare module '@material-ui/pickers/index' {
  declare module.exports: $Exports<'@material-ui/pickers'>;
}
declare module '@material-ui/pickers/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers'>;
}
declare module '@material-ui/pickers/LocalizationProvider.js' {
  declare module.exports: $Exports<'@material-ui/pickers/LocalizationProvider'>;
}
declare module '@material-ui/pickers/makePickerWithState-d83c633b.js' {
  declare module.exports: $Exports<'@material-ui/pickers/makePickerWithState-d83c633b'>;
}
declare module '@material-ui/pickers/Picker-858b30b6.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Picker-858b30b6'>;
}
declare module '@material-ui/pickers/Picker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Picker'>;
}
declare module '@material-ui/pickers/TimePicker-af76ca08.js' {
  declare module.exports: $Exports<'@material-ui/pickers/TimePicker-af76ca08'>;
}
declare module '@material-ui/pickers/TimePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/TimePicker'>;
}
declare module '@material-ui/pickers/useCanAutoFocus-1eacc580.js' {
  declare module.exports: $Exports<'@material-ui/pickers/useCanAutoFocus-1eacc580'>;
}
declare module '@material-ui/pickers/useKeyDown-5aaf69f9.js' {
  declare module.exports: $Exports<'@material-ui/pickers/useKeyDown-5aaf69f9'>;
}
