// System Preferences
export const SET_SYSTEM_PREFERENCE = 'SET_SYSTEM_PREFERENCE';

// Preferences
export const SET_PREFERENCE = 'SET_PREFERENCE';

// Notifications
export const UPDATE_PAUSE_NOTIFICATIONS_INFO = 'UPDATE_PAUSE_NOTIFICATIONS_INFO';

// Workspaces
export const SET_WORKSPACE = 'SET_WORKSPACE';

// Edit Workspace
export const UPDATE_EDIT_WORKSPACE_FORM = 'UPDATE_EDIT_WORKSPACE_FORM';

// General
export const UPDATE_CAN_GO_BACK = 'UPDATE_CAN_GO_BACK';
export const UPDATE_CAN_GO_FORWARD = 'UPDATE_CAN_GO_FORWARD';
export const UPDATE_DID_FAIL_LOAD = 'UPDATE_DID_FAIL_LOAD';
export const UPDATE_IS_DARK_MODE = 'UPDATE_IS_DARK_MODE';
export const UPDATE_IS_FULL_SCREEN = 'UPDATE_IS_FULL_SCREEN';
export const UPDATE_IS_DEFAULT_MAIL_CLIENT = 'UPDATE_IS_DEFAULT_MAIL_CLIENT';
export const UPDATE_IS_DEFAULT_WEB_BROWSER = 'UPDATE_IS_DEFAULT_WEB_BROWSER';
export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING';

// Find In Page
export const CLOSE_FIND_IN_PAGE = 'CLOSE_FIND_IN_PAGE';
export const OPEN_FIND_IN_PAGE = 'OPEN_FIND_IN_PAGE';
export const UPDATE_FIND_IN_PAGE_TEXT = 'UPDATE_FIND_IN_PAGE_TEXT';
export const UPDATE_FIND_IN_PAGE_MATCHES = 'UPDATE_FIND_IN_PAGE_MATCHES';

// Code Injection
export const UPDATE_CODE_INJECTION_FORM = 'UPDATE_CODE_INJECTION_FORM';

// Custom User Agent
export const UPDATE_CUSTOM_USER_AGENT_FORM = 'UPDATE_CUSTOM_USER_AGENT_FORM';

// Auth
export const UPDATE_AUTH_FORM = 'UPDATE_AUTH_FORM';

// About
export const ABOUT_CLOSE = 'ABOUT_CLOSE';
export const ABOUT_OPEN = 'ABOUT_OPEN';

// Add Workspace
export const ADD_WORKSPACE_GET_FAILED = 'ADD_WORKSPACE_GET_FAILED';
export const ADD_WORKSPACE_GET_REQUEST = 'ADD_WORKSPACE_GET_REQUEST';
export const ADD_WORKSPACE_GET_SUCCESS = 'ADD_WORKSPACE_GET_SUCCESS';
export const ADD_WORKSPACE_RESET = 'ADD_WORKSPACE_RESET';
export const ADD_WORKSPACE_UPDATE_CURRENT_QUERY = 'ADD_WORKSPACE_UPDATE_CURRENT_QUERY';
export const ADD_WORKSPACE_UPDATE_QUERY = 'ADD_WORKSPACE_UPDATE_QUERY';
export const ADD_WORKSPACE_UPDATE_FORM = 'ADD_WORKSPACE_UPDATE_FORM';
export const ADD_WORKSPACE_UPDATE_MODE = 'ADD_WORKSPACE_UPDATE_MODE';

// License Registration
export const LICENSE_REGISTRATION_FORM_UPDATE = 'LICENSE_REGISTRATION_FORM_UPDATE';

// Updater
export const UPDATE_UPDATER = 'UPDATE_UPDATER';
