// flow-typed signature: accfa14495c2f4c371e349d34e484e29
// flow-typed version: <<STUB>>/@date-io/date-fns_v1.3.13/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@date-io/date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@date-io/date-fns' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@date-io/date-fns/build/index.esm' {
  declare module.exports: any;
}

declare module '@date-io/date-fns/build' {
  declare module.exports: any;
}

declare module '@date-io/date-fns/rollup.config' {
  declare module.exports: any;
}

declare module '@date-io/date-fns/type' {
  declare module.exports: any;
}

// Filename aliases
declare module '@date-io/date-fns/build/index.esm.js' {
  declare module.exports: $Exports<'@date-io/date-fns/build/index.esm'>;
}
declare module '@date-io/date-fns/build/index' {
  declare module.exports: $Exports<'@date-io/date-fns/build'>;
}
declare module '@date-io/date-fns/build/index.js' {
  declare module.exports: $Exports<'@date-io/date-fns/build'>;
}
declare module '@date-io/date-fns/rollup.config.js' {
  declare module.exports: $Exports<'@date-io/date-fns/rollup.config'>;
}
declare module '@date-io/date-fns/type/index' {
  declare module.exports: $Exports<'@date-io/date-fns/type'>;
}
declare module '@date-io/date-fns/type/index.js' {
  declare module.exports: $Exports<'@date-io/date-fns/type'>;
}
