// flow-typed signature: 7b56cdae5f86174d30db706d7efa57f3
// flow-typed version: <<STUB>>/@rescripts/cli_v0.0.14/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rescripts/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rescripts/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rescripts/cli/bin/rescripts' {
  declare module.exports: any;
}

declare module '@rescripts/cli/loader' {
  declare module.exports: any;
}

declare module '@rescripts/cli/patch' {
  declare module.exports: any;
}

declare module '@rescripts/cli/scripts/build' {
  declare module.exports: any;
}

declare module '@rescripts/cli/scripts/start' {
  declare module.exports: any;
}

declare module '@rescripts/cli/scripts/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rescripts/cli/bin/rescripts.js' {
  declare module.exports: $Exports<'@rescripts/cli/bin/rescripts'>;
}
declare module '@rescripts/cli/loader.js' {
  declare module.exports: $Exports<'@rescripts/cli/loader'>;
}
declare module '@rescripts/cli/patch.js' {
  declare module.exports: $Exports<'@rescripts/cli/patch'>;
}
declare module '@rescripts/cli/scripts/build.js' {
  declare module.exports: $Exports<'@rescripts/cli/scripts/build'>;
}
declare module '@rescripts/cli/scripts/start.js' {
  declare module.exports: $Exports<'@rescripts/cli/scripts/start'>;
}
declare module '@rescripts/cli/scripts/test.js' {
  declare module.exports: $Exports<'@rescripts/cli/scripts/test'>;
}
